import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTheme } from '../../contexts/ThemeContext'
import { customerAPI } from '../../services/api'
import { 
  commodities, 
  equipmentTypes, 
  getQuickEstimate, 
  getRecommendedEquipment,
  formatCurrency,
  getMarketRateContext 
} from '../../services/pricingEngine'
import PageContainer from '../../components/PageContainer'
import Card from '../../components/Card'
import {
  Package, MapPin, Calendar, Truck, DollarSign, FileText,
  CheckCircle, AlertCircle, ArrowRight, ArrowLeft, Scale,
  Clock, Building, Hash, Loader, Info, TrendingUp, Mountain, 
  TreePine, Leaf, Recycle, Wrench, Building2, Hammer, 
  Layers, HardHat, TreePine as TreePineIcon, Users, Save
} from 'lucide-react'

interface LoadFormData {
  // Step 1: Material & Commodity
  materialType: string
  commodityDetails: string
  quantity: string
  quantityUnit: 'tons' | 'yards' | 'pieces' | 'trips'
  pieceCount: string
  selectedEquipment: string
  
  // Step 2: Locations & Contacts
  pickupLocation: string
  pickupAddress: string
  pickupContactName: string
  pickupContactPhone: string
  deliveryLocation: string
  deliveryAddress: string
  deliveryContactName: string
  deliveryContactPhone: string
  distance: number
  
  // Step 3: Schedule
  pickupDate: string
  pickupTimeStart: string
  pickupTimeEnd: string
  estimatedLoadingTime: string
  deliveryDate: string
  deliveryTimeStart: string
  deliveryTimeEnd: string
  estimatedUnloadingTime: string
  
  // Step 4: Requirements
  requiresScaleTicket: boolean
  requiresPermit: boolean
  requiresPrevailingWage: boolean
  specialInstructions: string
  
  // Step 5: Pricing & Payment
  rateMode: 'per_ton' | 'per_yard' | 'per_mile' | 'per_trip' | 'per_hour'
  rateAmount: string
  paymentTerms: 'net-15' | 'net-30' | 'net-45'
  quickPayEnabled: boolean
  loadPriority: 'normal' | 'high' | 'urgent'
  
  // Step 6: Accessorial Pre-Selection
  mayRequireDetention: boolean
  mayRequireLayover: boolean
  stopOffCount: number
  driverAssistNeeded: boolean
  
  // Step 7: Job Details
  jobCode: string
  siteName: string
  // Note: poNumber and loadId are auto-generated by system
  
  // System Recommendations
  suggestedEquipment: string[]
  estimatedCost: number
}

const LoadPostingWizard = () => {
  const { theme } = useTheme()
  const navigate = useNavigate()
  const [currentStep, setCurrentStep] = useState(1)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const [showSuccessModal, setShowSuccessModal] = useState(false)
  const [successMessage, setSuccessMessage] = useState('')
  const [formData, setFormData] = useState<LoadFormData>({
    materialType: '',
    commodityDetails: '',
    quantity: '',
    quantityUnit: 'tons',
    pieceCount: '',
    selectedEquipment: '',
    pickupLocation: '',
    pickupAddress: '',
    pickupContactName: '',
    pickupContactPhone: '',
    deliveryLocation: '',
    deliveryAddress: '',
    deliveryContactName: '',
    deliveryContactPhone: '',
    distance: 0,
    pickupDate: '',
    pickupTimeStart: '',
    pickupTimeEnd: '',
    estimatedLoadingTime: '30',
    deliveryDate: '',
    deliveryTimeStart: '',
    deliveryTimeEnd: '',
    estimatedUnloadingTime: '30',
    requiresScaleTicket: false,
    requiresPermit: false,
    requiresPrevailingWage: false,
    specialInstructions: '',
    rateMode: 'per_ton',
    rateAmount: '',
    paymentTerms: 'net-30',
    quickPayEnabled: false,
    loadPriority: 'normal',
    mayRequireDetention: false,
    mayRequireLayover: false,
    stopOffCount: 0,
    driverAssistNeeded: false,
    jobCode: '',
    siteName: '',
    suggestedEquipment: [],
    estimatedCost: 0
  })

  const totalSteps = 7

  // Icon mapping function
  const getIconComponent = (iconName: string) => {
    const iconProps = { size: 36, color: theme.colors.primary }
    switch (iconName) {
      case 'Mountain': return <Mountain {...iconProps} />
      case 'Truck': return <Truck {...iconProps} />
      case 'Layers': return <Layers {...iconProps} />
      case 'Wrench': return <Wrench {...iconProps} />
      case 'TreePine': return <TreePine {...iconProps} />
      case 'Building2': return <Building2 {...iconProps} />
      case 'Leaf': return <Leaf {...iconProps} />
      case 'Recycle': return <Recycle {...iconProps} />
      case 'Hammer': return <Hammer {...iconProps} />
      case 'Package': return <Package {...iconProps} />
      default: return <Package {...iconProps} />
    }
  }

  const materialTypes = [
    { value: 'aggregates', label: 'Aggregates (Crushed Stone, Gravel)', icon: 'Mountain', equipment: ['End Dump', 'Transfer Dump'] },
    { value: 'concrete', label: 'Ready-Mix Concrete', icon: 'Truck', equipment: ['Concrete Mixer'] },
    { value: 'asphalt', label: 'Asphalt', icon: 'Layers', equipment: ['End Dump', 'Transfer Dump'] },
    { value: 'steel', label: 'Steel & Rebar', icon: 'Wrench', equipment: ['Flatbed', 'Stepdeck'] },
    { value: 'lumber', label: 'Lumber & Building Materials', icon: 'TreePine', equipment: ['Flatbed', 'Dry Van'] },
    { value: 'equipment', label: 'Heavy Equipment', icon: 'Building2', equipment: ['Lowboy', 'RGN'] },
    { value: 'dirt', label: 'Dirt & Topsoil', icon: 'Leaf', equipment: ['End Dump', 'Transfer Dump'] },
    { value: 'debris', label: 'Demolition Debris', icon: 'Recycle', equipment: ['End Dump', 'Roll-off'] },
    { value: 'pipe', label: 'Pipe & Utilities', icon: 'Hammer', equipment: ['Flatbed', 'Extendable Flatbed'] },
    { value: 'other', label: 'Other Materials', icon: 'Package', equipment: ['Any'] }
  ]

  const handleNext = () => {
    if (currentStep < totalSteps) {
      setCurrentStep(currentStep + 1)
    }
  }

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1)
    }
  }

  const handleSaveDraft = async () => {
    try {
      // Calculate completion percentage
      const totalFields = Object.keys(formData).length
      const filledFields = Object.values(formData).filter(val => 
        val !== '' && val !== 0 && val !== false && (Array.isArray(val) ? val.length > 0 : true)
      ).length
      const completionPercentage = Math.round((filledFields / totalFields) * 100)

      // Save draft to localStorage (in production, save to API)
      const drafts = JSON.parse(localStorage.getItem('customer-drafts') || '[]')
      const draftId = `draft-${Date.now()}`
      
      drafts.push({
        id: draftId,
        ...formData,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        completionPercentage,
        status: 'DRAFT'
      })
      
      localStorage.setItem('customer-drafts', JSON.stringify(drafts))
      
      setSuccessMessage(`Draft saved successfully! (${completionPercentage}% complete)\n\nYou can continue editing from the Draft Loads page.`)
      setShowSuccessModal(true)
      
      setTimeout(() => {
        setShowSuccessModal(false)
        navigate('/draft-loads')
      }, 2000)
    } catch (error: any) {
      setSubmitError(`Error saving draft: ${error.message}`)
      setTimeout(() => setSubmitError(null), 5000)
    }
  }

  const handleSubmit = async () => {
    setIsSubmitting(true)
    setSubmitError(null)

    try {
      // Auto-generate Load ID and PO Number
      const timestamp = Date.now()
      const loadId = `LD-${timestamp.toString().slice(-6)}`
      const poNumber = `PO-${new Date().getFullYear()}-${timestamp.toString().slice(-5)}`
      
      // Prepare payload for API
      const payload = {
        loadId, // Auto-generated
        poNumber, // Auto-generated
        materialType: formData.materialType,
        commodityDetails: formData.commodityDetails,
        quantity: parseFloat(formData.quantity),
        quantityUnit: formData.quantityUnit,
        pickupLocation: formData.pickupLocation,
        pickupAddress: formData.pickupAddress,
        deliveryLocation: formData.deliveryLocation,
        deliveryAddress: formData.deliveryAddress,
        pickupDate: formData.pickupDate,
        pickupTimeStart: formData.pickupTimeStart,
        pickupTimeEnd: formData.pickupTimeEnd,
        deliveryDate: formData.deliveryDate,
        deliveryTimeStart: formData.deliveryTimeStart,
        deliveryTimeEnd: formData.deliveryTimeEnd,
        requiresScaleTicket: formData.requiresScaleTicket,
        requiresPermit: formData.requiresPermit,
        requiresPrevailingWage: formData.requiresPrevailingWage,
        specialInstructions: formData.specialInstructions,
        rateMode: formData.rateMode,
        rateAmount: parseFloat(formData.rateAmount),
        jobCode: formData.jobCode,
        siteName: formData.siteName
      }

      console.log('Submitting load to API:', payload)
      
      const response = await customerAPI.createLoad(payload)
      
      console.log('Load created successfully:', response)
      
      // Show success modal
      setSuccessMessage(`Load posted successfully!\n\nLoad ID: ${loadId}\nPO Number: ${poNumber}\nStatus: POSTED\n\nCarriers can now bid on your load.`)
      setShowSuccessModal(true)
      
      // Navigate after brief delay
      setTimeout(() => {
        setShowSuccessModal(false)
        navigate('/customer/loads')
      }, 3000)
      
    } catch (error: any) {
      console.error('Error creating load:', error)
      const errorMessage = error.response?.data?.error || error.message || 'Failed to post load'
      setSubmitError(`Error posting load: ${errorMessage}\n\nPlease try again or contact support.`)
    } finally {
      setIsSubmitting(false)
    }
  }

  const updateFormData = (field: keyof LoadFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    
    // Auto-suggest equipment when material type changes
    if (field === 'materialType') {
      const selected = materialTypes.find(m => m.value === value)
      if (selected) {
        setFormData(prev => ({ ...prev, suggestedEquipment: selected.equipment }))
      }
    }
  }

  const renderStepIndicator = () => (
    <Card padding="20px" style={{ marginBottom: '24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        {Array.from({ length: totalSteps }).map((_, index) => {
          const stepNum = index + 1
          const isActive = stepNum === currentStep
          const isCompleted = stepNum < currentStep
          
          return (
            <React.Fragment key={stepNum}>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', flex: 1 }}>
                <div style={{
                  width: '48px',
                  height: '48px',
                  borderRadius: '50%',
                  background: isCompleted ? theme.colors.success : isActive ? `linear-gradient(135deg, ${theme.colors.primary}, ${theme.colors.accent})` : theme.colors.border,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: 'white',
                  fontWeight: '700',
                  fontSize: '18px',
                  transition: 'all 0.3s ease',
                  boxShadow: isActive ? `0 4px 12px ${theme.colors.primary}40` : 'none'
                }}>
                  {isCompleted ? <CheckCircle size={24} /> : stepNum}
                </div>
                <span style={{
                  fontSize: '12px',
                  fontWeight: '600',
                  color: isActive ? theme.colors.textPrimary : theme.colors.textSecondary,
                  marginTop: '8px',
                  textAlign: 'center'
                }}>
                  {['Material', 'Locations', 'Schedule', 'Requirements', 'Pricing', 'Review'][index]}
                </span>
              </div>
              {stepNum < totalSteps && (
                <div style={{
                  flex: 1,
                  height: '3px',
                  background: stepNum < currentStep ? theme.colors.success : theme.colors.border,
                  margin: '0 8px',
                  marginBottom: '40px'
                }} />
              )}
            </React.Fragment>
          )
        })}
      </div>
    </Card>
  )

  const renderStep1 = () => (
    <Card title="Step 1: Material & Commodity" subtitle="What are you shipping?" icon={<Package size={20} color={theme.colors.primary} />}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginBottom: '24px' }}>
        {materialTypes.map((material) => (
          <div
            key={material.value}
            onClick={() => updateFormData('materialType', material.value)}
            style={{
              padding: '20px',
              background: formData.materialType === material.value ? `${theme.colors.primary}20` : theme.colors.background,
              border: `2px solid ${formData.materialType === material.value ? theme.colors.primary : theme.colors.border}`,
              borderRadius: '12px',
              cursor: 'pointer',
              textAlign: 'center',
              transition: 'all 0.2s ease'
            }}
            onMouseEnter={(e) => {
              if (formData.materialType !== material.value) {
                e.currentTarget.style.background = theme.colors.backgroundCardHover
              }
            }}
            onMouseLeave={(e) => {
              if (formData.materialType !== material.value) {
                e.currentTarget.style.background = theme.colors.background
              }
            }}
          >
            <div style={{ marginBottom: '8px' }}>{getIconComponent(material.icon)}</div>
            <div style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary }}>{material.label}</div>
          </div>
        ))}
      </div>

      {formData.materialType && (
        <div style={{ marginTop: '24px' }}>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
            Commodity Details
          </label>
          <input
            type="text"
            placeholder="e.g., 3/4 inch crushed stone, Ready-mix 3000 PSI"
            value={formData.commodityDetails}
            onChange={(e) => updateFormData('commodityDetails', e.target.value)}
            style={{
              width: '100%',
              padding: '14px 16px',
              background: theme.colors.inputBg,
              border: `2px solid ${theme.colors.inputBorder}`,
              borderRadius: '10px',
              fontSize: '15px',
              color: theme.colors.textPrimary,
              outline: 'none',
              transition: 'all 0.2s ease',
              marginBottom: '16px'
            }}
            onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
            onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
          />

          <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', gap: '16px' }}>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                Quantity *
              </label>
              <input
                type="number"
                placeholder="25"
                value={formData.quantity}
                onChange={(e) => updateFormData('quantity', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                Unit *
              </label>
              <select
                value={formData.quantityUnit}
                onChange={(e) => updateFormData('quantityUnit', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none',
                  cursor: 'pointer'
                }}
              >
                <option value="tons">Tons</option>
                <option value="yards">Yards</option>
                <option value="pieces">Pieces</option>
                <option value="trips">Trips</option>
              </select>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                Piece Count
              </label>
              <input
                type="number"
                placeholder="0"
                value={formData.pieceCount}
                onChange={(e) => updateFormData('pieceCount', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
          </div>

          {/* Equipment Selection */}
          {formData.suggestedEquipment.length > 0 && (
            <div style={{ marginTop: '24px' }}>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px' }}>
                Select Equipment Type *
              </label>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '12px', marginBottom: '16px' }}>
                {formData.suggestedEquipment.map((equip) => (
                  <div
                    key={equip}
                    onClick={() => updateFormData('selectedEquipment', equip)}
                    style={{
                      padding: '16px',
                      background: formData.selectedEquipment === equip ? `${theme.colors.primary}20` : theme.colors.backgroundSecondary,
                      border: `2px solid ${formData.selectedEquipment === equip ? theme.colors.primary : theme.colors.border}`,
                      borderRadius: '10px',
                      cursor: 'pointer',
                      textAlign: 'center',
                      transition: 'all 0.2s ease'
                    }}
                    onMouseEnter={(e) => {
                      if (formData.selectedEquipment !== equip) {
                        e.currentTarget.style.borderColor = theme.colors.primary
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (formData.selectedEquipment !== equip) {
                        e.currentTarget.style.borderColor = theme.colors.border
                      }
                    }}
                  >
                    <Truck size={20} color={formData.selectedEquipment === equip ? theme.colors.primary : theme.colors.textSecondary} style={{ marginBottom: '8px' }} />
                    <div style={{ fontSize: '14px', fontWeight: '600', color: formData.selectedEquipment === equip ? theme.colors.primary : theme.colors.textPrimary }}>
                      {equip}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {formData.suggestedEquipment.length > 0 && (
            <div style={{
              marginTop: '24px',
              padding: '16px',
              background: `${theme.colors.info}15`,
              border: `1px solid ${theme.colors.info}30`,
              borderRadius: '10px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                <Truck size={18} color={theme.colors.info} />
                <span style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary }}>
                  Recommended Equipment
                </span>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {formData.suggestedEquipment.map((equip) => (
                  <span
                    key={equip}
                    style={{
                      padding: '6px 12px',
                      background: theme.colors.info,
                      color: 'white',
                      borderRadius: '6px',
                      fontSize: '13px',
                      fontWeight: '600'
                    }}
                  >
                    {equip}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </Card>
  )

  const renderStep2 = () => (
    <Card title="Step 2: Locations & Contacts" subtitle="Where is the load going and who should carriers contact?" icon={<MapPin size={20} color={theme.colors.primary} />}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
        <div>
          <h3 style={{ fontSize: '18px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px' }}>
            Pickup Location
          </h3>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Location Name
            </label>
            <input
              type="text"
              placeholder="Acme Quarry North"
              value={formData.pickupLocation}
              onChange={(e) => updateFormData('pickupLocation', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Address
            </label>
            <input
              type="text"
              placeholder="123 Quarry Rd, Dallas, TX 75001"
              value={formData.pickupAddress}
              onChange={(e) => updateFormData('pickupAddress', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
              onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
              onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
            />
          </div>
          
          {/* Pickup Contact */}
          <div style={{ marginTop: '24px', padding: '16px', background: theme.colors.backgroundSecondary, borderRadius: '10px', border: `1px solid ${theme.colors.border}` }}>
            <h4 style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Users size={16} color={theme.colors.primary} />
              Pickup Contact
            </h4>
            <div style={{ marginBottom: '12px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '6px' }}>
                Contact Name *
              </label>
              <input
                type="text"
                placeholder="John Smith"
                value={formData.pickupContactName}
                onChange={(e) => updateFormData('pickupContactName', e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 14px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '6px' }}>
                Contact Phone *
              </label>
              <input
                type="tel"
                placeholder="(512) 555-0123"
                value={formData.pickupContactPhone}
                onChange={(e) => updateFormData('pickupContactPhone', e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 14px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
          </div>
        </div>

        <div>
          <h3 style={{ fontSize: '18px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px' }}>
            Delivery Location
          </h3>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Location Name
            </label>
            <input
              type="text"
              placeholder="I-35 Bridge Project"
              value={formData.deliveryLocation}
              onChange={(e) => updateFormData('deliveryLocation', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Address
            </label>
            <input
              type="text"
              placeholder="456 Construction Site, Dallas, TX 75002"
              value={formData.deliveryAddress}
              onChange={(e) => updateFormData('deliveryAddress', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
              onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
              onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
            />
          </div>
          
          {/* Delivery Contact */}
          <div style={{ marginTop: '24px', padding: '16px', background: theme.colors.backgroundSecondary, borderRadius: '10px', border: `1px solid ${theme.colors.border}` }}>
            <h4 style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Users size={16} color={theme.colors.primary} />
              Delivery Contact
            </h4>
            <div style={{ marginBottom: '12px' }}>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '6px' }}>
                Contact Name *
              </label>
              <input
                type="text"
                placeholder="Jane Doe"
                value={formData.deliveryContactName}
                onChange={(e) => updateFormData('deliveryContactName', e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 14px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '13px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '6px' }}>
                Contact Phone *
              </label>
              <input
                type="tel"
                placeholder="(512) 555-0456"
                value={formData.deliveryContactPhone}
                onChange={(e) => updateFormData('deliveryContactPhone', e.target.value)}
                style={{
                  width: '100%',
                  padding: '12px 14px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
          </div>
        </div>
      </div>

      <div style={{
        marginTop: '24px',
        padding: '16px',
        background: theme.colors.backgroundTertiary,
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px'
      }}>
        <div style={{
          width: '40px',
          height: '40px',
          background: `${theme.colors.success}20`,
          borderRadius: '8px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}>
          <MapPin size={20} color={theme.colors.success} />
        </div>
        <div>
          <div style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary }}>
            Estimated Distance: 28 miles
          </div>
          <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
            Metro/Zone haul (under 50 miles)
          </div>
        </div>
      </div>
    </Card>
  )

  const renderStep3 = () => (
    <Card title="Step 3: Schedule & Time Windows" subtitle="When do you need this load moved?" icon={<Calendar size={20} color={theme.colors.primary} />}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
        <div>
          <h3 style={{ fontSize: '18px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px' }}>
            Pickup Window
          </h3>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Pickup Date
            </label>
            <input
              type="date"
              value={formData.pickupDate}
              onChange={(e) => updateFormData('pickupDate', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
            />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                Start Time
              </label>
              <input
                type="time"
                value={formData.pickupTimeStart}
                onChange={(e) => updateFormData('pickupTimeStart', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                End Time
              </label>
              <input
                type="time"
                value={formData.pickupTimeEnd}
                onChange={(e) => updateFormData('pickupTimeEnd', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
              />
            </div>
          </div>
        </div>

        <div>
          <h3 style={{ fontSize: '18px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px' }}>
            Delivery Window
          </h3>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Delivery Date
            </label>
            <input
              type="date"
              value={formData.deliveryDate}
              onChange={(e) => updateFormData('deliveryDate', e.target.value)}
              style={{
                width: '100%',
                padding: '14px 16px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '10px',
                fontSize: '15px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
            />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                Start Time
              </label>
              <input
                type="time"
                value={formData.deliveryTimeStart}
                onChange={(e) => updateFormData('deliveryTimeStart', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
                End Time
              </label>
              <input
                type="time"
                value={formData.deliveryTimeEnd}
                onChange={(e) => updateFormData('deliveryTimeEnd', e.target.value)}
                style={{
                  width: '100%',
                  padding: '14px 16px',
                  background: theme.colors.inputBg,
                  border: `2px solid ${theme.colors.inputBorder}`,
                  borderRadius: '10px',
                  fontSize: '15px',
                  color: theme.colors.textPrimary,
                  outline: 'none'
                }}
                onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
                onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Loading/Unloading Time Estimates */}
      <div style={{
        marginTop: '24px',
        padding: '20px',
        background: theme.colors.backgroundSecondary,
        borderRadius: '10px',
        border: `1px solid ${theme.colors.border}`
      }}>
        <h4 style={{ fontSize: '16px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Clock size={18} color={theme.colors.info} />
          Estimated Duration
        </h4>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Loading Time (minutes)
            </label>
            <input
              type="number"
              placeholder="30"
              value={formData.estimatedLoadingTime}
              onChange={(e) => updateFormData('estimatedLoadingTime', e.target.value)}
              style={{
                width: '100%',
                padding: '12px 14px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '8px',
                fontSize: '14px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
              onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
              onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
            />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
              Unloading Time (minutes)
            </label>
            <input
              type="number"
              placeholder="30"
              value={formData.estimatedUnloadingTime}
              onChange={(e) => updateFormData('estimatedUnloadingTime', e.target.value)}
              style={{
                width: '100%',
                padding: '12px 14px',
                background: theme.colors.inputBg,
                border: `2px solid ${theme.colors.inputBorder}`,
                borderRadius: '8px',
                fontSize: '14px',
                color: theme.colors.textPrimary,
                outline: 'none'
              }}
              onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
              onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
            />
          </div>
        </div>
        <p style={{ fontSize: '12px', color: theme.colors.textSecondary, marginTop: '12px' }}>
          Total estimated time: {(parseInt(formData.estimatedLoadingTime || '0') + parseInt(formData.estimatedUnloadingTime || '0'))} minutes
        </p>
      </div>
    </Card>
  )

  const renderStep4 = () => (
    <Card title="Step 4: Requirements & Compliance" subtitle="Special requirements for this load" icon={<FileText size={20} color={theme.colors.primary} />}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        <label style={{
          padding: '16px',
          background: formData.requiresScaleTicket ? `${theme.colors.success}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.requiresScaleTicket ? theme.colors.success : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          transition: 'all 0.2s ease'
        }}>
          <input
            type="checkbox"
            checked={formData.requiresScaleTicket}
            onChange={(e) => updateFormData('requiresScaleTicket', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Scale size={18} color={theme.colors.textPrimary} />
              <span style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
                Requires Scale Ticket
              </span>
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              Weight verification required at pickup/delivery
            </div>
          </div>
        </label>

        <label style={{
          padding: '16px',
          background: formData.requiresPermit ? `${theme.colors.warning}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.requiresPermit ? theme.colors.warning : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          transition: 'all 0.2s ease'
        }}>
          <input
            type="checkbox"
            checked={formData.requiresPermit}
            onChange={(e) => updateFormData('requiresPermit', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <AlertCircle size={18} color={theme.colors.textPrimary} />
              <span style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
                Overweight Permit Required
              </span>
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              Load exceeds standard axle weight limits
            </div>
          </div>
        </label>

        <label style={{
          padding: '16px',
          background: formData.requiresPrevailingWage ? `${theme.colors.info}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.requiresPrevailingWage ? theme.colors.info : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          transition: 'all 0.2s ease'
        }}>
          <input
            type="checkbox"
            checked={formData.requiresPrevailingWage}
            onChange={(e) => updateFormData('requiresPrevailingWage', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Building size={18} color={theme.colors.textPrimary} />
              <span style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
                Prevailing Wage Project
              </span>
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              Public project requiring certified payroll
            </div>
          </div>
        </label>

        <div style={{ marginTop: '8px' }}>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
            Special Instructions
          </label>
          <textarea
            value={formData.specialInstructions}
            onChange={(e) => updateFormData('specialInstructions', e.target.value)}
            placeholder="Gate codes, contact information, delivery instructions..."
            rows={4}
            style={{
              width: '100%',
              padding: '14px 16px',
              background: theme.colors.inputBg,
              border: `2px solid ${theme.colors.inputBorder}`,
              borderRadius: '10px',
              fontSize: '15px',
              color: theme.colors.textPrimary,
              outline: 'none',
              fontFamily: 'inherit',
              resize: 'vertical'
            }}
          />
        </div>
      </div>
    </Card>
  )

  const renderStep5 = () => (
    <Card title="Step 5: Pricing & Rate Mode" subtitle="How do you want to price this load?" icon={<DollarSign size={20} color={theme.colors.primary} />}>
      <div style={{ marginBottom: '24px' }}>
        <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px' }}>
          Rate Mode
        </label>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '12px' }}>
          {[
            { value: 'per_ton', label: 'Per Ton', desc: 'Best for aggregates' },
            { value: 'per_yard', label: 'Per Yard', desc: 'Best for concrete' },
            { value: 'per_mile', label: 'Per Mile', desc: 'Best for OTR' },
            { value: 'per_trip', label: 'Per Trip', desc: 'Flat rate per delivery' },
            { value: 'per_hour', label: 'Per Hour', desc: 'Hourly rate + minimum' }
          ].map((mode) => (
            <div
              key={mode.value}
              onClick={() => updateFormData('rateMode', mode.value)}
              style={{
                padding: '16px',
                background: formData.rateMode === mode.value ? `${theme.colors.primary}20` : theme.colors.backgroundTertiary,
                border: `2px solid ${formData.rateMode === mode.value ? theme.colors.primary : theme.colors.border}`,
                borderRadius: '10px',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
            >
              <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '4px' }}>
                {mode.label}
              </div>
              <div style={{ fontSize: '12px', color: theme.colors.textSecondary }}>
                {mode.desc}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div>
        <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
          Rate Amount
        </label>
        <div style={{ position: 'relative' }}>
          <span style={{
            position: 'absolute',
            left: '16px',
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '18px',
            fontWeight: '700',
            color: theme.colors.textSecondary
          }}>
            $
          </span>
          <input
            type="number"
            step="0.01"
            placeholder="45.00"
            value={formData.rateAmount}
            onChange={(e) => updateFormData('rateAmount', e.target.value)}
            style={{
              width: '100%',
              padding: '14px 16px 14px 40px',
              background: theme.colors.inputBg,
              border: `2px solid ${theme.colors.inputBorder}`,
              borderRadius: '10px',
              fontSize: '18px',
              fontWeight: '600',
              color: theme.colors.textPrimary,
              outline: 'none'
            }}
            onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
            onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
          />
        </div>
        {formData.quantity && formData.rateAmount && (
          <div style={{
            marginTop: '16px',
            padding: '16px',
            background: `${theme.colors.success}15`,
            borderRadius: '10px'
          }}>
            <div style={{ fontSize: '14px', color: theme.colors.textSecondary, marginBottom: '4px' }}>
              Estimated Total
            </div>
            <div style={{ fontSize: '28px', fontWeight: '700', color: theme.colors.success }}>
              ${(parseFloat(formData.quantity) * parseFloat(formData.rateAmount)).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
            </div>
          </div>
        )}
      </div>

      {/* Payment Terms & Priority */}
      <div style={{
        marginTop: '24px',
        padding: '20px',
        background: theme.colors.backgroundSecondary,
        borderRadius: '10px',
        border: `1px solid ${theme.colors.border}`
      }}>
        <h4 style={{ fontSize: '16px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '16px' }}>
          Payment & Priority Settings
        </h4>
        
        <div style={{ marginBottom: '20px' }}>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px' }}>
            Payment Terms *
          </label>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
            {[
              { value: 'net-15', label: 'Net 15 Days' },
              { value: 'net-30', label: 'Net 30 Days' },
              { value: 'net-45', label: 'Net 45 Days' }
            ].map((term) => (
              <div
                key={term.value}
                onClick={() => updateFormData('paymentTerms', term.value)}
                style={{
                  padding: '14px',
                  background: formData.paymentTerms === term.value ? `${theme.colors.primary}20` : theme.colors.background,
                  border: `2px solid ${formData.paymentTerms === term.value ? theme.colors.primary : theme.colors.border}`,
                  borderRadius: '8px',
                  cursor: 'pointer',
                  textAlign: 'center',
                  fontSize: '14px',
                  fontWeight: '600',
                  color: formData.paymentTerms === term.value ? theme.colors.primary : theme.colors.textPrimary,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  if (formData.paymentTerms !== term.value) {
                    e.currentTarget.style.borderColor = theme.colors.primary
                  }
                }}
                onMouseLeave={(e) => {
                  if (formData.paymentTerms !== term.value) {
                    e.currentTarget.style.borderColor = theme.colors.border
                  }
                }}
              >
                {term.label}
              </div>
            ))}
          </div>
        </div>

        <label style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          padding: '14px',
          background: formData.quickPayEnabled ? `${theme.colors.success}15` : theme.colors.background,
          border: `2px solid ${formData.quickPayEnabled ? theme.colors.success : theme.colors.border}`,
          borderRadius: '8px',
          cursor: 'pointer',
          marginBottom: '20px'
        }}>
          <input
            type="checkbox"
            checked={formData.quickPayEnabled}
            onChange={(e) => updateFormData('quickPayEnabled', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div>
            <div style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary }}>
              Quick Pay Available (2% discount for 3-day payment)
            </div>
            <div style={{ fontSize: '12px', color: theme.colors.textSecondary }}>
              Carriers can opt for faster payment at a small discount
            </div>
          </div>
        </label>

        <div>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px' }}>
            Load Priority *
          </label>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
            {[
              { value: 'normal', label: 'Normal', color: theme.colors.info },
              { value: 'high', label: 'High Priority', color: theme.colors.warning },
              { value: 'urgent', label: 'Urgent', color: theme.colors.error }
            ].map((priority) => (
              <div
                key={priority.value}
                onClick={() => updateFormData('loadPriority', priority.value)}
                style={{
                  padding: '14px',
                  background: formData.loadPriority === priority.value ? `${priority.color}20` : theme.colors.background,
                  border: `2px solid ${formData.loadPriority === priority.value ? priority.color : theme.colors.border}`,
                  borderRadius: '8px',
                  cursor: 'pointer',
                  textAlign: 'center',
                  fontSize: '14px',
                  fontWeight: '600',
                  color: formData.loadPriority === priority.value ? priority.color : theme.colors.textPrimary,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  if (formData.loadPriority !== priority.value) {
                    e.currentTarget.style.borderColor = priority.color
                  }
                }}
                onMouseLeave={(e) => {
                  if (formData.loadPriority !== priority.value) {
                    e.currentTarget.style.borderColor = theme.colors.border
                  }
                }}
              >
                {priority.label}
              </div>
            ))}
          </div>
        </div>
      </div>
    </Card>
  )

  const renderStep6 = () => (
    <Card title="Step 6: Accessorial Services" subtitle="Select potential additional services" icon={<AlertCircle size={20} color={theme.colors.primary} />}>
      <div style={{
        padding: '16px',
        background: `${theme.colors.info}15`,
        border: `1px solid ${theme.colors.info}30`,
        borderRadius: '10px',
        marginBottom: '24px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
          <Info size={18} color={theme.colors.info} />
          <span style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary }}>
            Pre-selection helps carriers understand potential additional costs
          </span>
        </div>
        <p style={{ fontSize: '13px', color: theme.colors.textSecondary, marginLeft: '26px' }}>
          These are optional services that MAY be needed. Actual charges only apply if service is used.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        <label style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          padding: '16px',
          background: formData.mayRequireDetention ? `${theme.colors.warning}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.mayRequireDetention ? theme.colors.warning : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer'
        }}>
          <input
            type="checkbox"
            checked={formData.mayRequireDetention}
            onChange={(e) => updateFormData('mayRequireDetention', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '4px' }}>
              May Require Detention
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              $60/hour after 2 hours at pickup or delivery (Platform takes 25%, carrier receives 75%)
            </div>
          </div>
        </label>

        <label style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          padding: '16px',
          background: formData.mayRequireLayover ? `${theme.colors.warning}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.mayRequireLayover ? theme.colors.warning : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer'
        }}>
          <input
            type="checkbox"
            checked={formData.mayRequireLayover}
            onChange={(e) => updateFormData('mayRequireLayover', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '4px' }}>
              May Require Layover
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              $250/day when driver cannot complete delivery same day (Platform takes 25%, carrier receives 75%)
            </div>
          </div>
        </label>

        <div style={{
          padding: '16px',
          background: theme.colors.backgroundTertiary,
          border: `2px solid ${theme.colors.border}`,
          borderRadius: '10px'
        }}>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '12px' }}>
              Number of Stop-Offs
            </label>
            <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
              <button
                type="button"
                onClick={() => updateFormData('stopOffCount', Math.max(0, formData.stopOffCount - 1))}
                style={{
                  width: '40px',
                  height: '40px',
                  background: theme.colors.backgroundCard,
                  border: `2px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  fontSize: '20px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  cursor: 'pointer'
                }}
              >
                -
              </button>
              <div style={{
                flex: 1,
                textAlign: 'center',
                fontSize: '24px',
                fontWeight: '700',
                color: theme.colors.primary
              }}>
                {formData.stopOffCount}
              </div>
              <button
                type="button"
                onClick={() => updateFormData('stopOffCount', formData.stopOffCount + 1)}
                style={{
                  width: '40px',
                  height: '40px',
                  background: theme.colors.backgroundCard,
                  border: `2px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  fontSize: '20px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  cursor: 'pointer'
                }}
              >
                +
              </button>
            </div>
            <p style={{ fontSize: '12px', color: theme.colors.textSecondary, marginTop: '8px', textAlign: 'center' }}>
              $50 per additional stop
            </p>
          </div>
        </div>

        <label style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          padding: '16px',
          background: formData.driverAssistNeeded ? `${theme.colors.info}15` : theme.colors.backgroundTertiary,
          border: `2px solid ${formData.driverAssistNeeded ? theme.colors.info : theme.colors.border}`,
          borderRadius: '10px',
          cursor: 'pointer'
        }}>
          <input
            type="checkbox"
            checked={formData.driverAssistNeeded}
            onChange={(e) => updateFormData('driverAssistNeeded', e.target.checked)}
            style={{ width: '20px', height: '20px', cursor: 'pointer' }}
          />
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '4px' }}>
              Driver Assist Required
            </div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary }}>
              Driver needs to help with loading/unloading (varies by carrier)
            </div>
          </div>
        </label>
      </div>
    </Card>
  )

  const renderStep7 = () => (
    <Card title="Step 7: Job Details & Review" subtitle="Final details and confirmation" icon={<Hash size={20} color={theme.colors.primary} />}>
      {/* Auto-Generated Load Identifiers */}
      <div style={{
        padding: '20px',
        background: `${theme.colors.success}15`,
        border: `1px solid ${theme.colors.success}30`,
        borderRadius: '10px',
        marginBottom: '24px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
          <CheckCircle size={20} color={theme.colors.success} />
          <span style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
            System-Generated Load Identifiers
          </span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginLeft: '28px' }}>
          <div>
            <div style={{ fontSize: '12px', color: theme.colors.textSecondary, marginBottom: '4px' }}>
              BOL Number (Driver uses at pickup)
            </div>
            <div style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.success }}>
              BOL-{new Date().toISOString().split('T')[0].replace(/-/g, '')}-{Math.floor(Math.random() * 9000) + 1000}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '12px', color: theme.colors.textSecondary, marginBottom: '4px' }}>
              Load ID (Internal tracking)
            </div>
            <div style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.success }}>
              LOAD-{Math.random().toString(36).substring(2, 8).toUpperCase()}
            </div>
          </div>
        </div>
        <p style={{ fontSize: '12px', color: theme.colors.textSecondary, marginTop: '12px', marginLeft: '28px' }}>
          These numbers are automatically generated when you post this load. The BOL number will be used by the driver at pickup.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '32px' }}>
        <div>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
            Job Code (Your Internal Reference)
          </label>
          <input
            type="text"
            placeholder="Highway-35-Project"
            value={formData.jobCode}
            onChange={(e) => updateFormData('jobCode', e.target.value)}
            style={{
              width: '100%',
              padding: '14px 16px',
              background: theme.colors.inputBg,
              border: `2px solid ${theme.colors.inputBorder}`,
              borderRadius: '10px',
              fontSize: '15px',
              color: theme.colors.textPrimary,
              outline: 'none'
            }}
            onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
            onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
          />
          <p style={{ fontSize: '11px', color: theme.colors.textSecondary, marginTop: '6px' }}>
            Your accounting/project code (optional)
          </p>
        </div>
        <div>
          <label style={{ display: 'block', fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, marginBottom: '8px' }}>
            Site Name
          </label>
          <input
            type="text"
            placeholder="I-35 Bridge Project Site B"
            value={formData.siteName}
            onChange={(e) => updateFormData('siteName', e.target.value)}
            style={{
              width: '100%',
              padding: '14px 16px',
              background: theme.colors.inputBg,
              border: `2px solid ${theme.colors.inputBorder}`,
              borderRadius: '10px',
              fontSize: '15px',
              color: theme.colors.textPrimary,
              outline: 'none'
            }}
            onFocus={(e) => e.currentTarget.style.borderColor = theme.colors.inputFocus}
            onBlur={(e) => e.currentTarget.style.borderColor = theme.colors.inputBorder}
          />
          <p style={{ fontSize: '11px', color: theme.colors.textSecondary, marginTop: '6px' }}>
            Delivery site name for driver reference
          </p>
        </div>
      </div>

      {/* Review Summary */}
      <div style={{
        padding: '24px',
        background: theme.colors.backgroundTertiary,
        borderRadius: '12px',
        border: `1px solid ${theme.colors.border}`
      }}>
        <h3 style={{ fontSize: '20px', fontWeight: '700', color: theme.colors.textPrimary, marginBottom: '20px' }}>
          Load Summary
        </h3>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Material</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
              {formData.commodityDetails || 'Not specified'}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Quantity</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
              {formData.quantity} {formData.quantityUnit}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Pickup</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
              {formData.pickupLocation || 'Not specified'}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Delivery</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
              {formData.deliveryLocation || 'Not specified'}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Pickup Date</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.textPrimary }}>
              {formData.pickupDate || 'Not specified'}
            </div>
          </div>
          <div>
            <div style={{ fontSize: '13px', color: theme.colors.textSecondary, marginBottom: '4px' }}>Rate</div>
            <div style={{ fontSize: '15px', fontWeight: '600', color: theme.colors.success }}>
              ${formData.rateAmount}/{formData.rateMode.replace('per_', '')}
            </div>
          </div>
        </div>
      </div>
    </Card>
  )

  return (
    <PageContainer
      title="Post New Load"
      subtitle="Create a new load posting for carriers"
      icon={Package}
    >
      {renderStepIndicator()}
      
      {currentStep === 1 && renderStep1()}
      {currentStep === 2 && renderStep2()}
      {currentStep === 3 && renderStep3()}
      {currentStep === 4 && renderStep4()}
      {currentStep === 5 && renderStep5()}
      {currentStep === 6 && renderStep6()}
      {currentStep === 7 && renderStep7()}

      {/* Navigation Buttons */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        marginTop: '32px',
        gap: '16px'
      }}>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button
            onClick={handlePrevious}
            disabled={currentStep === 1}
            style={{
              padding: '14px 32px',
              background: currentStep === 1 ? theme.colors.backgroundTertiary : theme.colors.backgroundCard,
              color: currentStep === 1 ? theme.colors.textSecondary : theme.colors.textPrimary,
              border: `2px solid ${theme.colors.border}`,
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '600',
              cursor: currentStep === 1 ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              transition: 'all 0.2s ease'
            }}
          >
            <ArrowLeft size={18} />
            Previous
          </button>

          {/* Save as Draft Button */}
          <button
            type="button"
            onClick={handleSaveDraft}
            style={{
              padding: '14px 24px',
              background: theme.colors.backgroundCard,
              color: theme.colors.textPrimary,
              border: `2px solid ${theme.colors.warning}`,
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              transition: 'all 0.2s ease'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = `${theme.colors.warning}20`
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = theme.colors.backgroundCard
            }}
          >
            <Save size={18} />
            Save Draft
          </button>
        </div>

        {currentStep < totalSteps ? (
          <button
            onClick={handleNext}
            style={{
              padding: '14px 32px',
              background: `linear-gradient(135deg, ${theme.colors.primary} 0%, ${theme.colors.accent} 100%)`,
              color: 'white',
              border: 'none',
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: `0 4px 12px ${theme.colors.primary}40`,
              transition: 'all 0.2s ease'
            }}
            onMouseEnter={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
            onMouseLeave={(e) => e.currentTarget.style.transform = 'translateY(0)'}
          >
            Next
            <ArrowRight size={18} />
          </button>
        ) : (
          <button
            onClick={handleSubmit}
            disabled={isSubmitting}
            style={{
              padding: '14px 32px',
              background: isSubmitting 
                ? theme.colors.backgroundTertiary 
                : `linear-gradient(135deg, ${theme.colors.success} 0%, #059669 100%)`,
              color: 'white',
              border: 'none',
              borderRadius: '12px',
              fontSize: '15px',
              fontWeight: '600',
              cursor: isSubmitting ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: `0 4px 12px ${theme.colors.success}40`,
              transition: 'all 0.2s ease',
              opacity: isSubmitting ? 0.7 : 1
            }}
            onMouseEnter={(e) => !isSubmitting && (e.currentTarget.style.transform = 'translateY(-2px)')}
            onMouseLeave={(e) => !isSubmitting && (e.currentTarget.style.transform = 'translateY(0)')}
          >
            {isSubmitting ? (
              <>
                <Loader size={18} style={{ animation: 'spin 1s linear infinite' }} />
                Posting Load...
              </>
            ) : (
              <>
                <CheckCircle size={18} />
                Post Load
              </>
            )}
          </button>
        )}
      </div>

      {/* Success Modal */}
      {showSuccessModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(0,0,0,0.8)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 10000,
          backdropFilter: 'blur(4px)'
        }}>
          <div style={{
            background: theme.colors.backgroundCard,
            borderRadius: '16px',
            padding: '40px',
            maxWidth: '500px',
            width: '90%',
            textAlign: 'center',
            boxShadow: `0 20px 60px ${theme.colors.primary}40`
          }}>
            <div style={{
              width: '80px',
              height: '80px',
              background: `${theme.colors.success}20`,
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              margin: '0 auto 24px'
            }}>
              <CheckCircle size={48} color={theme.colors.success} />
            </div>
            
            <h2 style={{ fontSize: '28px', fontWeight: '700', color: theme.colors.textPrimary, marginBottom: '16px' }}>
              Success!
            </h2>
            
            <p style={{ 
              fontSize: '16px', 
              color: theme.colors.textSecondary, 
              lineHeight: '1.6',
              marginBottom: 0,
              whiteSpace: 'pre-line'
            }}>
              {successMessage}
            </p>
          </div>
        </div>
      )}
    </PageContainer>
  )
}

export default LoadPostingWizard

