import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTheme } from '../contexts/ThemeContext'
import PageContainer from '../components/shared/PageContainer'
import Card from '../components/ui/Card'
import { formatNumber, formatCurrency, formatCompactCurrency, formatPercentage } from '../utils/formatters';
import { US_STATES } from '../constants/states'
import AnimatedCounter from '../components/enhanced/AnimatedCounter'

import { 
  Truck, Package, MapPin, DollarSign, Clock, TrendingUp, 
  AlertCircle, CheckCircle, Filter, Search, Eye, 
  Calendar, Navigation, Zap, Star, Loader, Send, X, Building,
  Heart, ArrowUpDown, Crosshair, Check, XCircle, MapPinned
} from 'lucide-react'

// Load Board Listing Interface - Shows limited info for security
interface LoadBoardListing {
  id: string // Auto-generated by system
  contractDate: string // When customer posted load
  customer: string // Customer name
  commodity: string // Material type
  equipment: string // Equipment needed
  
  // Pickup Info (CITY ONLY - security feature)
  pickupCity: string // Only city shown on board
  pickupState: string
  pickupDate: string // Separate date field
  pickupETA: string // Separate time window
  
  // Delivery Info (CITY ONLY - security feature)  
  deliveryCity: string // Only city shown on board
  deliveryState: string
  deliveryDate: string // Separate date field
  deliveryETA: string // Separate time window
  
  // Financial
  rateMode: 'PER_TON' | 'PER_LOAD' | 'PER_MILE' | 'PER_YARD'
  rate: number // Numeric rate
  units: number // Tonnage, loads, etc.
  estimatedRevenue: number
  
  // Logistics
  mileage: number // Distance
  
  // Additional
  requirements: string[]
  priority: 'high' | 'medium' | 'low'
  quickPayEligible: boolean
  
  // Full details (hidden until bid accepted)
  fullPickupAddress?: string
  fullDeliveryAddress?: string
  pickupContact?: { name: string; phone: string }
  deliveryContact?: { name: string; phone: string }
}

type SortOption = 'distance' | 'revenue' | 'date' | 'rate' | 'none'
type BidStatus = 'pending' | 'accepted' | 'rejected' | 'none'

interface CarrierLocation {
  city: string
  state: string
  lat?: number
  lng?: number
}

const CarrierLoadBoardPage = () => {
  const navigate = useNavigate()
  const { theme } = useTheme()
  
  const [loads, setLoads] = useState<LoadBoardListing[]>([])
  const [loading, setLoading] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterEquipment, setFilterEquipment] = useState('all')
  const [filterPriority, setFilterPriority] = useState('all')
  
  // Location Filters
  const [pickupCity, setPickupCity] = useState('')
  const [pickupState, setPickupState] = useState('')
  const [deliveryCity, setDeliveryCity] = useState('')
  const [deliveryState, setDeliveryState] = useState('')
  
  // Date Filters
  const [pickupDateFrom, setPickupDateFrom] = useState('')
  const [pickupDateTo, setPickupDateTo] = useState('')
  
  // NEW: Sorting
  const [sortBy, setSortBy] = useState<SortOption>('none')
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc')
  
  // NEW: Distance Filter
  const [carrierLocation, setCarrierLocation] = useState<CarrierLocation>({ city: 'Dallas', state: 'TX' })
  const [maxDistance, setMaxDistance] = useState<number>(0) // 0 = no filter
  
  // NEW: Favorites (stored in localStorage)
  const [favorites, setFavorites] = useState<string[]>([])
  
  // NEW: Bid Status Tracking (stored in localStorage)
  const [bidStatuses, setBidStatuses] = useState<Record<string, BidStatus>>({})
  
  const [selectedLoad, setSelectedLoad] = useState<LoadBoardListing | null>(null)
  const [showBidModal, setShowBidModal] = useState(false)
  const [bidAmount, setBidAmount] = useState('')
  const [bidNotes, setBidNotes] = useState('')
  const [isSubmittingBid, setIsSubmittingBid] = useState(false)

  // Mock data - matches your workflow spec
  const mockLoads: LoadBoardListing[] = [
    {
      id: 'LT-2025-0001',
      contractDate: '2025-10-09',
      customer: 'ABC Construction',
      commodity: 'Crushed Limestone',
      equipment: 'End Dump',
      pickupCity: 'Austin',
      pickupState: 'TX',
      pickupDate: '2025-10-15',
      pickupETA: '8:00 AM - 10:00 AM',
      deliveryCity: 'San Antonio',
      deliveryState: 'TX',
      deliveryDate: '2025-10-15',
      deliveryETA: '2:00 PM - 4:00 PM',
      rateMode: 'PER_TON',
      rate: 75,
      units: 18.5,
      estimatedRevenue: 1387.50,
      mileage: 80,
      requirements: ['Scale Ticket Required', 'DOT Compliant'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '1234 Quarry Rd, Austin, TX 78701',
      fullDeliveryAddress: '5678 Construction Site, San Antonio, TX 78205',
      pickupContact: { name: 'Tom Martinez', phone: '(512) 555-0123' },
      deliveryContact: { name: 'John Foreman', phone: '(210) 555-0456' }
    },
    {
      id: 'LT-2025-0002',
      contractDate: '2025-10-09',
      customer: 'Downtown Builders',
      commodity: 'Concrete Mix (3000 PSI)',
      equipment: 'Mixer',
      pickupCity: 'Round Rock',
      pickupState: 'TX',
      pickupDate: '2025-10-16',
      pickupETA: '6:00 AM - 8:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-16',
      deliveryETA: '10:00 AM - 12:00 PM',
      rateMode: 'PER_YARD',
      rate: 180,
      units: 8,
      estimatedRevenue: 1440,
      mileage: 22,
      requirements: ['Time Sensitive (90min limit)', 'Pour scheduled'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '789 Plant Rd, Round Rock, TX 78664',
      fullDeliveryAddress: '321 Downtown Site, Austin, TX 78701',
      pickupContact: { name: 'Plant Manager', phone: '(512) 555-0789' },
      deliveryContact: { name: 'Site Foreman', phone: '(512) 555-0321' }
    },
    {
      id: 'LT-2025-0003',
      contractDate: '2025-10-08',
      customer: 'Highway Construction LLC',
      commodity: 'Gravel Base',
      equipment: 'End Dump',
      pickupCity: 'Georgetown',
      pickupState: 'TX',
      pickupDate: '2025-10-14',
      pickupETA: '7:00 AM - 9:00 AM',
      deliveryCity: 'Pflugerville',
      deliveryState: 'TX',
      deliveryDate: '2025-10-14',
      deliveryETA: '11:00 AM - 1:00 PM',
      rateMode: 'PER_TON',
      rate: 52,
      units: 25,
      estimatedRevenue: 1300,
      mileage: 18,
      requirements: ['Scale Ticket Required'],
      priority: 'medium',
      quickPayEligible: false,
      fullPickupAddress: '456 Gravel Pit Rd, Georgetown, TX 78626',
      fullDeliveryAddress: '789 Highway 130, Pflugerville, TX 78660',
      pickupContact: { name: 'Pit Supervisor', phone: '(512) 555-0456' },
      deliveryContact: { name: 'Highway Crew Lead', phone: '(512) 555-0789' }
    },
    {
      id: 'LT-2025-0004',
      contractDate: '2025-10-09',
      customer: 'Metro Development Corp',
      commodity: 'Ready-Mix Concrete (4000 PSI)',
      equipment: 'Mixer',
      pickupCity: 'Austin',
      pickupState: 'TX',
      pickupDate: '2025-10-17',
      pickupETA: '5:00 AM - 7:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-17',
      deliveryETA: '8:00 AM - 10:00 AM',
      rateMode: 'PER_YARD',
      rate: 195,
      units: 12,
      estimatedRevenue: 2340,
      mileage: 8,
      requirements: ['Time Sensitive (90min limit)', 'Early Morning Pour'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '123 Concrete Plant, Austin, TX 78704',
      fullDeliveryAddress: '456 Metro Tower Site, Austin, TX 78701',
      pickupContact: { name: 'Batch Plant Operator', phone: '(512) 555-0111' },
      deliveryContact: { name: 'Pour Coordinator', phone: '(512) 555-0222' }
    },
    {
      id: 'LT-2025-0005',
      contractDate: '2025-10-07',
      customer: 'Riverside Contractors',
      commodity: 'Sand',
      equipment: 'End Dump',
      pickupCity: 'Bastrop',
      pickupState: 'TX',
      pickupDate: '2025-10-12',
      pickupETA: '9:00 AM - 11:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-12',
      deliveryETA: '1:00 PM - 3:00 PM',
      rateMode: 'PER_TON',
      rate: 38,
      units: 22,
      estimatedRevenue: 836,
      mileage: 32,
      requirements: ['Scale Ticket Required', 'Tarp Required'],
      priority: 'low',
      quickPayEligible: false,
      fullPickupAddress: '999 Sand Pit Ln, Bastrop, TX 78602',
      fullDeliveryAddress: '555 Riverside Project, Austin, TX 78702',
      pickupContact: { name: 'Pit Manager', phone: '(512) 555-0999' },
      deliveryContact: { name: 'Project Manager', phone: '(512) 555-0555' }
    },
    {
      id: 'LT-2025-0006',
      contractDate: '2025-10-10',
      customer: 'Phoenix Mega Development',
      commodity: 'Crushed Granite',
      equipment: 'End Dump',
      pickupCity: 'Phoenix',
      pickupState: 'AZ',
      pickupDate: '2025-10-18',
      pickupETA: '7:00 AM - 9:00 AM',
      deliveryCity: 'Scottsdale',
      deliveryState: 'AZ',
      deliveryDate: '2025-10-18',
      deliveryETA: '11:00 AM - 1:00 PM',
      rateMode: 'PER_TON',
      rate: 85,
      units: 20,
      estimatedRevenue: 1700,
      mileage: 25,
      requirements: ['Scale Ticket Required', 'DOT Compliant'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '456 Quarry Rd, Phoenix, AZ 85001',
      fullDeliveryAddress: '789 Luxury Resort Site, Scottsdale, AZ 85251',
      pickupContact: { name: 'Quarry Supervisor', phone: '(602) 555-0123' },
      deliveryContact: { name: 'Site Manager', phone: '(480) 555-0456' }
    },
    {
      id: 'LT-2025-0007',
      contractDate: '2025-10-09',
      customer: 'LA Metro Construction',
      commodity: 'Ready-Mix Concrete',
      equipment: 'Mixer',
      pickupCity: 'Los Angeles',
      pickupState: 'CA',
      pickupDate: '2025-10-16',
      pickupETA: '5:00 AM - 7:00 AM',
      deliveryCity: 'Santa Monica',
      deliveryState: 'CA',
      deliveryDate: '2025-10-16',
      deliveryETA: '8:00 AM - 10:00 AM',
      rateMode: 'PER_YARD',
      rate: 220,
      units: 10,
      estimatedRevenue: 2200,
      mileage: 18,
      requirements: ['Time Sensitive (90min limit)', 'Early Morning Pour'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '123 Concrete Plant, Los Angeles, CA 90001',
      fullDeliveryAddress: '456 Beachfront Project, Santa Monica, CA 90401',
      pickupContact: { name: 'Batch Operator', phone: '(213) 555-0111' },
      deliveryContact: { name: 'Pour Coordinator', phone: '(310) 555-0222' }
    },
    {
      id: 'LT-2025-0008',
      contractDate: '2025-10-08',
      customer: 'Miami Beach Developers',
      commodity: 'Sand',
      equipment: 'End Dump',
      pickupCity: 'Miami',
      pickupState: 'FL',
      pickupDate: '2025-10-14',
      pickupETA: '8:00 AM - 10:00 AM',
      deliveryCity: 'Fort Lauderdale',
      deliveryState: 'FL',
      deliveryDate: '2025-10-14',
      deliveryETA: '12:00 PM - 2:00 PM',
      rateMode: 'PER_TON',
      rate: 42,
      units: 18,
      estimatedRevenue: 756,
      mileage: 30,
      requirements: ['Scale Ticket Required', 'Tarp Required'],
      priority: 'medium',
      quickPayEligible: false,
      fullPickupAddress: '789 Sand Pit Rd, Miami, FL 33101',
      fullDeliveryAddress: '321 Beach Resort Site, Fort Lauderdale, FL 33301',
      pickupContact: { name: 'Pit Manager', phone: '(305) 555-0789' },
      deliveryContact: { name: 'Project Manager', phone: '(954) 555-0321' }
    },
    {
      id: 'LT-2025-0009',
      contractDate: '2025-10-11',
      customer: 'Seattle Infrastructure Group',
      commodity: 'Asphalt',
      equipment: 'End Dump',
      pickupCity: 'Seattle',
      pickupState: 'WA',
      pickupDate: '2025-10-19',
      pickupETA: '6:00 AM - 8:00 AM',
      deliveryCity: 'Tacoma',
      deliveryState: 'WA',
      deliveryDate: '2025-10-19',
      deliveryETA: '10:00 AM - 12:00 PM',
      rateMode: 'PER_TON',
      rate: 68,
      units: 24,
      estimatedRevenue: 1632,
      mileage: 34,
      requirements: ['Hot Load', 'DOT Compliant'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '456 Asphalt Plant, Seattle, WA 98101',
      fullDeliveryAddress: '789 Highway Project, Tacoma, WA 98401',
      pickupContact: { name: 'Plant Manager', phone: '(206) 555-0456' },
      deliveryContact: { name: 'Paving Crew Lead', phone: '(253) 555-0789' }
    },
    {
      id: 'LT-2025-0010',
      contractDate: '2025-10-10',
      customer: 'Denver Mountain Builders',
      commodity: 'Gravel',
      equipment: 'End Dump',
      pickupCity: 'Denver',
      pickupState: 'CO',
      pickupDate: '2025-10-17',
      pickupETA: '7:00 AM - 9:00 AM',
      deliveryCity: 'Boulder',
      deliveryState: 'CO',
      deliveryDate: '2025-10-17',
      deliveryETA: '11:00 AM - 1:00 PM',
      rateMode: 'PER_TON',
      rate: 55,
      units: 20,
      estimatedRevenue: 1100,
      mileage: 28,
      requirements: ['Scale Ticket Required'],
      priority: 'medium',
      quickPayEligible: false,
      fullPickupAddress: '123 Gravel Pit, Denver, CO 80201',
      fullDeliveryAddress: '456 Mountain Lodge Site, Boulder, CO 80301',
      pickupContact: { name: 'Pit Supervisor', phone: '(303) 555-0123' },
      deliveryContact: { name: 'Site Foreman', phone: '(303) 555-0456' }
    },
    {
      id: 'LT-2025-0011',
      contractDate: '2025-10-09',
      customer: 'Atlanta Metro Transit',
      commodity: 'Concrete (5000 PSI)',
      equipment: 'Mixer',
      pickupCity: 'Atlanta',
      pickupState: 'GA',
      pickupDate: '2025-10-15',
      pickupETA: '5:30 AM - 7:30 AM',
      deliveryCity: 'Marietta',
      deliveryState: 'GA',
      deliveryDate: '2025-10-15',
      deliveryETA: '9:00 AM - 11:00 AM',
      rateMode: 'PER_YARD',
      rate: 210,
      units: 15,
      estimatedRevenue: 3150,
      mileage: 22,
      requirements: ['Time Sensitive (90min limit)', 'Transit Project'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '789 Concrete Plant, Atlanta, GA 30301',
      fullDeliveryAddress: '321 Transit Station Site, Marietta, GA 30060',
      pickupContact: { name: 'Plant Operator', phone: '(404) 555-0789' },
      deliveryContact: { name: 'Transit Project Manager', phone: '(770) 555-0321' }
    },
    {
      id: 'LT-2025-0012',
      contractDate: '2025-10-12',
      customer: 'Chicago Skyline Development',
      commodity: 'Crushed Stone',
      equipment: 'End Dump',
      pickupCity: 'Chicago',
      pickupState: 'IL',
      pickupDate: '2025-10-20',
      pickupETA: '6:00 AM - 8:00 AM',
      deliveryCity: 'Naperville',
      deliveryState: 'IL',
      deliveryDate: '2025-10-20',
      deliveryETA: '10:00 AM - 12:00 PM',
      rateMode: 'PER_TON',
      rate: 72,
      units: 22,
      estimatedRevenue: 1584,
      mileage: 29,
      requirements: ['Scale Ticket Required', 'DOT Compliant'],
      priority: 'medium',
      quickPayEligible: true,
      fullPickupAddress: '456 Quarry Dr, Chicago, IL 60601',
      fullDeliveryAddress: '789 Tower Site, Naperville, IL 60540',
      pickupContact: { name: 'Quarry Manager', phone: '(312) 555-0456' },
      deliveryContact: { name: 'Construction Manager', phone: '(630) 555-0789' }
    }
  ]

  // Load favorites and bid statuses from localStorage
  useEffect(() => {
    const savedFavorites = localStorage.getItem('carrier_favorites')
    if (savedFavorites) {
      try {
        setFavorites(JSON.parse(savedFavorites))
      } catch (e) {
        console.error('Error loading favorites:', e)
      }
    }

    const savedBidStatuses = localStorage.getItem('carrier_bid_statuses')
    if (savedBidStatuses) {
      try {
        setBidStatuses(JSON.parse(savedBidStatuses))
      } catch (e) {
        console.error('Error loading bid statuses:', e)
      }
    }

    const savedCarrierLocation = localStorage.getItem('carrier_location')
    if (savedCarrierLocation) {
      try {
        setCarrierLocation(JSON.parse(savedCarrierLocation))
      } catch (e) {
        console.error('Error loading carrier location:', e)
      }
    }
  }, [])

  // Load data
  useEffect(() => {
    setLoads(mockLoads)
  }, [])

  // Save favorites to localStorage
  useEffect(() => {
    localStorage.setItem('carrier_favorites', JSON.stringify(favorites))
  }, [favorites])

  // Save bid statuses to localStorage
  useEffect(() => {
    localStorage.setItem('carrier_bid_statuses', JSON.stringify(bidStatuses))
  }, [bidStatuses])

  // Save carrier location to localStorage
  useEffect(() => {
    localStorage.setItem('carrier_location', JSON.stringify(carrierLocation))
  }, [carrierLocation])

  // Utility: Calculate distance between two points (simple approximation)
  const calculateDistance = (load: LoadBoardListing): number => {
    // Simple approximation - in real app, use actual geocoding
    // For now, we'll use the mileage from carrier location to pickup as rough estimate
    // This is a placeholder - real implementation would geocode carrier location and pickup
    return load.mileage
  }

  // Utility: Toggle favorite
  const toggleFavorite = (loadId: string) => {
    setFavorites(prev => {
      if (prev.includes(loadId)) {
        return prev.filter(id => id !== loadId)
      } else {
        return [...prev, loadId]
      }
    })
  }

  // Utility: Get bid status for a load
  const getBidStatus = (loadId: string): BidStatus => {
    return bidStatuses[loadId] || 'none'
  }

  // Utility: Update bid status
  const updateBidStatus = (loadId: string, status: BidStatus) => {
    setBidStatuses(prev => ({
      ...prev,
      [loadId]: status
    }))
  }

  const handleSubmitBid = async () => {
    if (!selectedLoad) return
    
    setIsSubmittingBid(true)
    
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      console.log('Bid submitted:', {
        loadId: selectedLoad.id,
        bidAmount: bidAmount || 'Posted Rate',
        notes: bidNotes
      })
      
      // Mark bid as pending
      updateBidStatus(selectedLoad.id, 'pending')
      
      alert(
        `✅ BID SUBMITTED SUCCESSFULLY!\n\n` +
        `Load: ${selectedLoad.id}\n` +
        `Customer: ${selectedLoad.customer}\n` +
        `Your Bid: $${bidAmount || selectedLoad.estimatedRevenue}\n\n` +
        `Customer will review your bid.\n` +
        `You'll be notified when accepted.\n\n` +
        `Next Steps:\n` +
        `1. Customer accepts bid\n` +
        `2. Rate Confirmation automatically generated & sent\n` +
        `3. You sign as dispatch/owner (30 min deadline)\n` +
        `4. Driver has 30 MINUTES to accept via SMS\n` +
        `5. Load moves to "My Loads" with full details\n\n` +
        `📄 Rate Con will be sent to both you and your driver automatically!`
      )
      
      setShowBidModal(false)
      setSelectedLoad(null)
      setBidAmount('')
      setBidNotes('')
    } catch (error) {
      console.error('Error submitting bid:', error)
      alert('❌ Error submitting bid. Please try again.')
    } finally {
      setIsSubmittingBid(false)
    }
  }

  // Filter and sort loads
  const filteredLoads = mockLoads
    .filter(load => {
      const matchesSearch = searchTerm === '' || 
        load.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
        load.commodity.toLowerCase().includes(searchTerm.toLowerCase()) ||
        load.customer.toLowerCase().includes(searchTerm.toLowerCase()) ||
        load.pickupCity.toLowerCase().includes(searchTerm.toLowerCase()) ||
        load.deliveryCity.toLowerCase().includes(searchTerm.toLowerCase())
      
      const matchesEquipment = filterEquipment === 'all' || load.equipment === filterEquipment
      const matchesPriority = filterPriority === 'all' || load.priority === filterPriority
      
      // Location filters
      const matchesPickupCity = pickupCity === '' || 
        load.pickupCity.toLowerCase().includes(pickupCity.toLowerCase())
      const matchesPickupState = pickupState === '' || 
        load.pickupState.toLowerCase() === pickupState.toLowerCase()
      const matchesDeliveryCity = deliveryCity === '' || 
        load.deliveryCity.toLowerCase().includes(deliveryCity.toLowerCase())
      const matchesDeliveryState = deliveryState === '' || 
        load.deliveryState.toLowerCase() === deliveryState.toLowerCase()
      
      // Date filters
      const loadPickupDate = new Date(load.pickupDate)
      const matchesDateFrom = pickupDateFrom === '' || 
        loadPickupDate >= new Date(pickupDateFrom)
      const matchesDateTo = pickupDateTo === '' || 
        loadPickupDate <= new Date(pickupDateTo)
      
      // Distance filter
      const distance = calculateDistance(load)
      const matchesDistance = maxDistance === 0 || distance <= maxDistance
      
      return matchesSearch && matchesEquipment && matchesPriority && 
             matchesPickupCity && matchesPickupState && 
             matchesDeliveryCity && matchesDeliveryState &&
             matchesDateFrom && matchesDateTo && matchesDistance
    })
    .sort((a, b) => {
      if (sortBy === 'none') return 0
      
      let comparison = 0
      
      if (sortBy === 'distance') {
        comparison = calculateDistance(a) - calculateDistance(b)
      } else if (sortBy === 'revenue') {
        comparison = a.estimatedRevenue - b.estimatedRevenue
      } else if (sortBy === 'date') {
        comparison = new Date(a.pickupDate).getTime() - new Date(b.pickupDate).getTime()
      } else if (sortBy === 'rate') {
        comparison = a.rate - b.rate
      }
      
      return sortDirection === 'asc' ? comparison : -comparison
    })

  const stats = {
    total: mockLoads.length,
    available: mockLoads.length,
    totalRevenue: mockLoads.reduce((sum, l) => sum + l.estimatedRevenue, 0),
    quickPayEligible: mockLoads.filter(l => l.quickPayEligible).length,
    highPriority: mockLoads.filter(l => l.priority === 'high').length
  }

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return theme.colors.error
      case 'medium': return theme.colors.warning
      case 'low': return theme.colors.info
      default: return theme.colors.textSecondary
    }
  }

  const getRateModeDisplay = (mode: string) => {
    return mode.replace('PER_', '/').toLowerCase()
  }

  return (
    <PageContainer title="Load Board" subtitle="Available loads from customers - Submit bids to win freight" icon={Package as any}>
      {/* Stats Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px', marginBottom: '24px' }}>
        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: theme.colors.backgroundTertiary, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Package size={28} color={theme.colors.textSecondary} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>AVAILABLE LOADS</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.total}</p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: `${theme.colors.success}20`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <DollarSign size={28} color={theme.colors.success} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>TOTAL REVENUE</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.success, margin: 0 }}>
                <AnimatedCounter value={stats.totalRevenue} format="currency" />
              </p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: theme.colors.backgroundTertiary, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Zap size={28} color={theme.colors.textSecondary} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>QUICKPAY</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.quickPayEligible}</p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: theme.colors.backgroundTertiary, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Star size={28} color={theme.colors.textSecondary} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>HOT LOADS</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.highPriority}</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Search and Filters */}
      <Card padding="20px" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
          <div style={{ flex: '1 1 300px', position: 'relative' }}>
            <Search size={18} color={theme.colors.textSecondary} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              type="text"
              placeholder="Search by load ID, commodity, customer, or city..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{
                width: '100%',
                padding: '12px 12px 12px 42px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none',
                transition: 'all 0.2s ease'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <select
            value={filterEquipment}
            onChange={(e) => setFilterEquipment(e.target.value)}
            style={{
              padding: '12px 16px',
              background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: '8px',
              color: theme.colors.textPrimary,
              fontSize: '14px',
              cursor: 'pointer',
              outline: 'none',
              minWidth: '180px',
              transition: 'all 0.2s ease'
            }}
            onFocus={(e) => {
              e.target.style.borderColor = theme.colors.primary
              e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
            }}
            onBlur={(e) => {
              e.target.style.borderColor = theme.colors.border
              e.target.style.boxShadow = 'none'
            }}
          >
            <option value="all" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>All Equipment</option>
            <option value="End Dump" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>End Dump</option>
            <option value="Mixer" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Mixer</option>
            <option value="Flatbed" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Flatbed</option>
            <option value="Lowboy" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Lowboy</option>
          </select>

          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            style={{
              padding: '12px 16px',
              background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: '8px',
              color: theme.colors.textPrimary,
              fontSize: '14px',
              cursor: 'pointer',
              outline: 'none',
              minWidth: '180px',
              transition: 'all 0.2s ease'
            }}
            onFocus={(e) => {
              e.target.style.borderColor = theme.colors.primary
              e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
            }}
            onBlur={(e) => {
              e.target.style.borderColor = theme.colors.border
              e.target.style.boxShadow = 'none'
            }}
          >
            <option value="all" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>All Priority</option>
            <option value="high" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>High Priority</option>
            <option value="medium" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Medium Priority</option>
            <option value="low" style={{ background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Low Priority</option>
          </select>
        </div>

        {/* Sorting & Distance Controls */}
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap', marginTop: '16px', paddingTop: '16px', borderTop: `1px solid ${theme.colors.border}` }}>
          <div style={{ flex: '1 1 200px' }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <ArrowUpDown size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Sort By
            </label>
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as SortOption)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                cursor: 'pointer',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            >
              <option value="none">None</option>
              <option value="distance">Distance (miles)</option>
              <option value="revenue">Revenue</option>
              <option value="date">Pickup Date</option>
              <option value="rate">Rate</option>
            </select>
          </div>

          <div style={{ flex: '0 0 120px' }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              Direction
            </label>
            <select
              value={sortDirection}
              onChange={(e) => setSortDirection(e.target.value as 'asc' | 'desc')}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                cursor: 'pointer',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            >
              <option value="asc">Low → High</option>
              <option value="desc">High → Low</option>
            </select>
          </div>

          <div style={{ flex: '1 1 200px' }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <Crosshair size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Max Distance (miles)
            </label>
            <input
              type="number"
              placeholder="No limit"
              value={maxDistance || ''}
              onChange={(e) => setMaxDistance(parseInt(e.target.value) || 0)}
              min="0"
              step="50"
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <div style={{ flex: '1 1 200px' }}>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <MapPinned size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Your Location
            </label>
            <div style={{ display: 'flex', gap: '8px' }}>
              <input
                type="text"
                placeholder="City"
                value={carrierLocation.city}
                onChange={(e) => setCarrierLocation(prev => ({ ...prev, city: e.target.value }))}
                style={{
                  flex: 2,
                  padding: '10px 12px',
                  background: theme.colors.background,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  color: theme.colors.textPrimary,
                  fontSize: '14px',
                  outline: 'none'
                }}
                onFocus={(e) => {
                  e.target.style.borderColor = theme.colors.primary
                  e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                }}
                onBlur={(e) => {
                  e.target.style.borderColor = theme.colors.border
                  e.target.style.boxShadow = 'none'
                }}
              />
              <input
                type="text"
                placeholder="ST"
                value={carrierLocation.state}
                onChange={(e) => setCarrierLocation(prev => ({ ...prev, state: e.target.value.toUpperCase() }))}
                maxLength={2}
                style={{
                  flex: 1,
                  padding: '10px 12px',
                  background: theme.colors.background,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  color: theme.colors.textPrimary,
                  fontSize: '14px',
                  outline: 'none',
                  textTransform: 'uppercase'
                }}
                onFocus={(e) => {
                  e.target.style.borderColor = theme.colors.primary
                  e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                }}
                onBlur={(e) => {
                  e.target.style.borderColor = theme.colors.border
                  e.target.style.boxShadow = 'none'
                }}
              />
            </div>
          </div>
        </div>

        {/* Location & Date Filters */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginTop: '16px', paddingTop: '16px', borderTop: `1px solid ${theme.colors.border}` }}>
          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <MapPin size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Pickup City
            </label>
            <input
              type="text"
              placeholder="e.g. Austin, Phoenix..."
              value={pickupCity}
              onChange={(e) => setPickupCity(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              Pickup State
            </label>
            <select
              value={pickupState}
              onChange={(e) => setPickupState(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                cursor: 'pointer',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            >
              <option value="">All States</option>
              {US_STATES.map(state => (
                <option key={state.code} value={state.code}>{state.name} ({state.code})</option>
              ))}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <Navigation size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Delivery City
            </label>
            <input
              type="text"
              placeholder="e.g. Dallas, Miami..."
              value={deliveryCity}
              onChange={(e) => setDeliveryCity(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              Delivery State
            </label>
            <select
              value={deliveryState}
              onChange={(e) => setDeliveryState(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                cursor: 'pointer',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            >
              <option value="">All States</option>
              {US_STATES.map(state => (
                <option key={state.code} value={state.code}>{state.name} ({state.code})</option>
              ))}
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              <Calendar size={14} style={{ display: 'inline', marginRight: '6px' }} />
              Pickup Date From
            </label>
            <input
              type="date"
              value={pickupDateFrom}
              onChange={(e) => setPickupDateFrom(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              Pickup Date To
            </label>
            <input
              type="date"
              value={pickupDateTo}
              onChange={(e) => setPickupDateTo(e.target.value)}
              style={{
                width: '100%',
                padding: '10px 12px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          {/* Clear Filters Button */}
          <div style={{ display: 'flex', alignItems: 'flex-end' }}>
            <button
              onClick={() => {
                setSearchTerm('')
                setFilterEquipment('all')
                setFilterPriority('all')
                setPickupCity('')
                setPickupState('')
                setDeliveryCity('')
                setDeliveryState('')
                setPickupDateFrom('')
                setPickupDateTo('')
                setSortBy('none')
                setSortDirection('desc')
                setMaxDistance(0)
              }}
              style={{
                width: '100%',
                padding: '10px 16px',
                background: theme.colors.backgroundCard,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textSecondary,
                fontSize: '14px',
                fontWeight: '600',
                cursor: 'pointer',
                transition: 'all 0.2s ease'
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = theme.colors.primary
                e.currentTarget.style.color = '#FFFFFF'
                e.currentTarget.style.borderColor = theme.colors.primary
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = theme.colors.backgroundCard
                e.currentTarget.style.color = theme.colors.textSecondary
                e.currentTarget.style.borderColor = theme.colors.border
              }}
            >
              <X size={16} style={{ display: 'inline', marginRight: '6px' }} />
              Clear All Filters
            </button>
          </div>
        </div>
      </Card>

      {/* Loads List */}
      <Card padding="20px">
        <h3 style={{ fontSize: '18px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 20px 0' }}>
          Available Loads ({filteredLoads.length})
        </h3>

        {filteredLoads.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 20px' }}>
            <Package size={48} color={theme.colors.textSecondary} style={{ opacity: 0.5 }} />
            <p style={{ marginTop: '16px', color: theme.colors.textSecondary }}>No loads found matching your filters</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {filteredLoads.map((load) => (
              <div
                key={load.id}
                style={{
                  background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
                  borderRadius: '12px',
                  padding: '24px',
                  border: `2px solid ${load.priority === 'high' ? theme.colors.error : theme.colors.border}`,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.12)'
                  e.currentTarget.style.transform = 'translateY(-2px)'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.boxShadow = 'none'
                  e.currentTarget.style.transform = 'translateY(0)'
                }}
              >
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px', flexWrap: 'wrap' }}>
                      <span style={{ fontSize: '20px', fontWeight: '700', color: theme.colors.textPrimary }}>
                        {load.id}
                      </span>
                      
                      {/* Bid Status Badge */}
                      {getBidStatus(load.id) === 'pending' && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.info}20`,
                          color: theme.colors.info,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          textTransform: 'uppercase',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Clock size={12} />
                          BID PENDING
                        </span>
                      )}
                      {getBidStatus(load.id) === 'accepted' && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.success}20`,
                          color: theme.colors.success,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          textTransform: 'uppercase',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Check size={12} />
                          BID ACCEPTED
                        </span>
                      )}
                      {getBidStatus(load.id) === 'rejected' && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.error}20`,
                          color: theme.colors.error,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          textTransform: 'uppercase',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <XCircle size={12} />
                          BID REJECTED
                        </span>
                      )}
                      
                      {load.priority === 'high' && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.error}20`,
                          color: theme.colors.error,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          textTransform: 'uppercase',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Star size={12} />
                          HOT LOAD
                        </span>
                      )}
                      {load.quickPayEligible && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.warning}20`,
                          color: theme.colors.warning,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Zap size={12} />
                          QuickPay
                        </span>
                      )}
                    </div>
                    <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0' }}>
                      <Building size={14} style={{ display: 'inline', marginRight: '6px' }} />
                      {load.customer} • Posted {load.contractDate}
                    </p>
                    <p style={{ fontSize: '16px', fontWeight: '600', color: theme.colors.textPrimary, margin: 0 }}>
                      {load.commodity} • {load.units} {load.rateMode.replace('PER_', '').toLowerCase()}{load.units > 1 ? 's' : ''}
                    </p>
                  </div>

                  <div style={{ textAlign: 'right', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
                    <div style={{ minWidth: '140px', marginRight: '8px', textAlign: 'right' }}>
                      <p style={{ fontSize: '32px', fontWeight: '700', color: theme.colors.success, margin: '0 0 4px 0', lineHeight: '1.1', wordBreak: 'break-word', whiteSpace: 'nowrap' }}>
                        ${formatNumber(load.estimatedRevenue)}
                      </p>
                      <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: 0, lineHeight: '1.2', whiteSpace: 'nowrap' }}>
                        ${load.rate}{getRateModeDisplay(load.rateMode)}
                      </p>
                    </div>
                    
                    {/* Favorite Button */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        toggleFavorite(load.id)
                      }}
                      style={{
                        background: 'none',
                        border: 'none',
                        cursor: 'pointer',
                        padding: '8px',
                        borderRadius: '8px',
                        transition: 'all 0.2s ease',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = theme.colors.backgroundCardHover
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'none'
                      }}
                      title={favorites.includes(load.id) ? 'Remove from favorites' : 'Add to favorites'}
                    >
                      <Heart 
                        size={24} 
                        color={theme.colors.textSecondary}
                        fill={favorites.includes(load.id) ? theme.colors.textSecondary : 'none'}
                        strokeWidth={favorites.includes(load.id) ? 0 : 2}
                      />
                    </button>
                  </div>
                </div>

                {/* Route Info - CITY ONLY (Security Feature) */}
                <div style={{ 
                  display: 'grid', 
                  gridTemplateColumns: '1fr auto 1fr', 
                  gap: '16px', 
                  alignItems: 'center',
                  padding: '16px',
                  background: theme.colors.background,
                  borderRadius: '8px',
                  marginBottom: '16px'
                }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                      <MapPin size={16} color={theme.colors.textSecondary} />
                      <span style={{ fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, textTransform: 'uppercase' }}>
                        Pickup
                      </span>
                    </div>
                    <p style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                      {load.pickupCity}, {load.pickupState}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: '0 0 2px 0' }}>
                      <Clock size={12} style={{ display: 'inline', marginRight: '4px' }} />
                      {load.pickupDate}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textTertiary, margin: 0 }}>
                      {load.pickupETA}
                    </p>
                    <p style={{ fontSize: '11px', color: theme.colors.textTertiary, margin: '4px 0 0 0', fontStyle: 'italic' }}>
                      * Full address in Rate Con
                    </p>
                  </div>

                  <div style={{ textAlign: 'center' }}>
                    <Navigation size={20} color={theme.colors.textSecondary} />
                    <p style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, margin: '4px 0 0 0' }}>
                      {load.mileage} mi
                    </p>
                  </div>

                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                      <MapPin size={16} color={theme.colors.textSecondary} />
                      <span style={{ fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, textTransform: 'uppercase' }}>
                        Delivery
                      </span>
                    </div>
                    <p style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                      {load.deliveryCity}, {load.deliveryState}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: '0 0 2px 0' }}>
                      <Clock size={12} style={{ display: 'inline', marginRight: '4px' }} />
                      {load.deliveryDate}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textTertiary, margin: 0 }}>
                      {load.deliveryETA}
                    </p>
                    <p style={{ fontSize: '11px', color: theme.colors.textTertiary, margin: '4px 0 0 0', fontStyle: 'italic' }}>
                      * Full address in Rate Con
                    </p>
                  </div>
                </div>

                {/* Equipment & Requirements */}
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap', marginBottom: '16px' }}>
                  <div style={{
                    padding: '6px 12px',
                    background: theme.colors.backgroundTertiary,
                    border: `1px solid ${theme.colors.border}`,
                    borderRadius: '6px',
                    fontSize: '13px',
                    fontWeight: '600',
                    color: theme.colors.textSecondary,
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px'
                  }}>
                    <Truck size={14} color={theme.colors.textSecondary} />
                    {load.equipment}
                  </div>

                  {load.requirements.map((req, idx) => (
                    <span
                      key={idx}
                      style={{
                        padding: '6px 12px',
                        background: theme.colors.backgroundTertiary,
                        border: `1px solid ${theme.colors.border}`,
                        color: theme.colors.textSecondary,
                        borderRadius: '6px',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <AlertCircle size={12} color={theme.colors.textSecondary} />
                      {req}
                    </span>
                  ))}
                </div>

                {/* Action Button */}
                <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                  {getBidStatus(load.id) === 'none' ? (
                    <button
                      onClick={() => {
                        setSelectedLoad(load)
                        setShowBidModal(true)
                      }}
                      style={{
                        padding: '12px 24px',
                        background: 'transparent',
                        color: theme.colors.textSecondary,
                        border: `1px solid ${theme.colors.border}`,
                        borderRadius: '8px',
                        fontSize: '14px',
                        fontWeight: '600',
                        cursor: 'pointer',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                        transition: 'all 0.2s ease'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = theme.colors.backgroundCardHover
                        e.currentTarget.style.color = theme.colors.textPrimary
                        e.currentTarget.style.borderColor = theme.colors.primary
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'transparent'
                        e.currentTarget.style.color = theme.colors.textSecondary
                        e.currentTarget.style.borderColor = theme.colors.border
                      }}
                    >
                      <Send size={16} />
                      Submit Bid
                    </button>
                  ) : (
                    <div style={{
                      padding: '12px 24px',
                      background: theme.colors.backgroundCardHover,
                      border: `2px solid ${
                        getBidStatus(load.id) === 'pending' ? theme.colors.info :
                        getBidStatus(load.id) === 'accepted' ? theme.colors.success :
                        theme.colors.error
                      }`,
                      borderRadius: '8px',
                      fontSize: '14px',
                      fontWeight: '600',
                      color: theme.colors.textSecondary,
                      display: 'flex',
                      alignItems: 'center',
                      gap: '8px'
                    }}>
                      {getBidStatus(load.id) === 'pending' && (
                        <>
                          <Clock size={16} color={theme.colors.textSecondary} />
                          Awaiting Response
                        </>
                      )}
                      {getBidStatus(load.id) === 'accepted' && (
                        <>
                          <CheckCircle size={16} color={theme.colors.success} />
                          Bid Accepted
                        </>
                      )}
                      {getBidStatus(load.id) === 'rejected' && (
                        <>
                          <XCircle size={16} color={theme.colors.error} />
                          Bid Rejected
                        </>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Bid Submission Modal */}
      {showBidModal && selectedLoad && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0, 0, 0, 0.75)',
            backdropFilter: 'blur(4px)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '20px'
          }}
          onClick={() => !isSubmittingBid && setShowBidModal(false)}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              background: theme.name === 'dark' ? '#1e293b' : theme.colors.backgroundCard,
              borderRadius: '16px',
              maxWidth: '700px',
              width: '100%',
              maxHeight: '90vh',
              overflow: 'auto',
              boxShadow: '0 24px 48px rgba(0, 0, 0, 0.3)'
            }}
          >
            {/* Modal Header */}
            <div style={{ padding: '24px', borderBottom: `1px solid ${theme.colors.border}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h2 style={{ fontSize: '22px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                  Submit Bid
                </h2>
                <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: 0 }}>
                  {selectedLoad.id} - {selectedLoad.commodity}
                </p>
              </div>
              <button
                onClick={() => !isSubmittingBid && setShowBidModal(false)}
                disabled={isSubmittingBid}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  padding: '8px',
                  borderRadius: '6px',
                  transition: 'all 0.2s ease',
                  opacity: isSubmittingBid ? 0.5 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.background = theme.colors.backgroundCardHover)}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'none')}
              >
                <X size={24} color={theme.colors.textSecondary} />
              </button>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px' }}>
              {/* Load Summary */}
              <div style={{ padding: '16px', background: theme.colors.background, borderRadius: '12px', marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '12px' }}>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>CUSTOMER</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.customer}</p>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>POSTED</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.contractDate}</p>
                  </div>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>ROUTE</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0 }}>
                      {selectedLoad.pickupCity} → {selectedLoad.deliveryCity} ({selectedLoad.mileage} mi)
                    </p>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>EQUIPMENT</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.equipment}</p>
                  </div>
                </div>
              </div>

              {/* Security Notice */}
              <div style={{
                padding: '12px 16px',
                background: `${theme.colors.warning}10`,
                border: `1px solid ${theme.colors.warning}30`,
                borderRadius: '8px',
                marginBottom: '24px',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '12px'
              }}>
                <AlertCircle size={18} color={theme.colors.warning} style={{ flexShrink: 0, marginTop: '2px' }} />
                <div>
                  <p style={{ fontSize: '13px', fontWeight: '600', color: theme.colors.warning, margin: '0 0 4px 0' }}>
                    Address Privacy Notice
                  </p>
                  <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: 0, lineHeight: 1.5 }}>
                    Full pickup & delivery addresses, along with contact information, will be revealed in the Rate Confirmation after your bid is accepted by the customer.
                  </p>
                </div>
              </div>

              {/* Bid Amount */}
              <div style={{ marginBottom: '20px' }}>
                <label style={{
                  fontSize: '14px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  display: 'block',
                  marginBottom: '8px'
                }}>
                  Your Bid Amount (Optional)
                </label>
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: theme.colors.textSecondary, fontSize: '14px', fontWeight: '600' }}>$</span>
                  <input
                    type="number"
                    value={bidAmount}
                    onChange={(e) => setBidAmount(e.target.value)}
                    placeholder={selectedLoad.estimatedRevenue.toString()}
                    disabled={isSubmittingBid}
                    style={{
                      width: '100%',
                      padding: '12px 12px 12px 28px',
                      background: theme.colors.background,
                      border: `1px solid ${theme.colors.border}`,
                      borderRadius: '8px',
                      color: theme.colors.textPrimary,
                      fontSize: '16px',
                      fontWeight: '600',
                      outline: 'none',
                      transition: 'all 0.2s ease'
                    }}
                    onFocus={(e) => {
                      e.target.style.borderColor = theme.colors.primary
                      e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                    }}
                    onBlur={(e) => {
                      e.target.style.borderColor = theme.colors.border
                      e.target.style.boxShadow = 'none'
                    }}
                  />
                </div>
                <p style={{ fontSize: '12px', color: theme.colors.textTertiary, margin: '6px 0 0 0' }}>
                  Tip: Leave blank to bid at posted rate (${formatNumber(selectedLoad.estimatedRevenue)})
                </p>
              </div>

              {/* Bid Notes */}
              <div style={{ marginBottom: '24px' }}>
                <label style={{
                  fontSize: '14px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  display: 'block',
                  marginBottom: '8px'
                }}>
                  Notes to Customer (Optional)
                </label>
                <textarea
                  value={bidNotes}
                  onChange={(e) => setBidNotes(e.target.value)}
                  placeholder="Add any questions, special capabilities, or notes for the customer..."
                  disabled={isSubmittingBid}
                  rows={4}
                  style={{
                    width: '100%',
                    padding: '12px',
                    background: theme.colors.background,
                    border: `1px solid ${theme.colors.border}`,
                    borderRadius: '8px',
                    color: theme.colors.textPrimary,
                    fontSize: '14px',
                    outline: 'none',
                    resize: 'vertical',
                    fontFamily: 'inherit',
                    transition: 'all 0.2s ease'
                  }}
                  onFocus={(e) => {
                    e.target.style.borderColor = theme.colors.primary
                    e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = theme.colors.border
                    e.target.style.boxShadow = 'none'
                  }}
                />
              </div>

              {/* Workflow Info */}
              <div style={{
                padding: '16px',
                background: `${theme.colors.info}10`,
                border: `1px solid ${theme.colors.info}30`,
                borderRadius: '8px',
                marginBottom: '24px'
              }}>
                <p style={{ fontSize: '13px', fontWeight: '600', color: theme.colors.info, margin: '0 0 8px 0' }}>
                  Next Steps After Bid Submission:
                </p>
                <ol style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  <li>Customer reviews your bid</li>
                  <li>If accepted, Rate Confirmation is generated</li>
                  <li>You (dispatch/owner) sign Rate Confirmation</li>
                  <li>Driver receives SMS and has <strong style={{ color: theme.colors.error }}>30 MINUTES</strong> to accept</li>
                  <li>If accepted, load moves to "My Loads" with full details</li>
                  <li>If not accepted in 30 min, load returns to Load Board</li>
                </ol>
              </div>
            </div>

            {/* Modal Footer */}
            <div style={{ padding: '20px 24px', borderTop: `1px solid ${theme.colors.border}`, display: 'flex', gap: '12px', justifyContent: 'flex-end' }}>
              <button
                onClick={() => {
                  setShowBidModal(false)
                  setSelectedLoad(null)
                  setBidAmount('')
                  setBidNotes('')
                }}
                disabled={isSubmittingBid}
                style={{
                  padding: '12px 24px',
                  background: theme.colors.backgroundTertiary,
                  color: theme.colors.textPrimary,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: '600',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s ease',
                  opacity: isSubmittingBid ? 0.5 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.background = theme.colors.backgroundCardHover)}
                onMouseLeave={(e) => (e.currentTarget.style.background = theme.colors.backgroundTertiary)}
              >
                Cancel
              </button>
              <button
                onClick={handleSubmitBid}
                disabled={isSubmittingBid}
                style={{
                  padding: '12px 28px',
                  background: isSubmittingBid
                    ? theme.colors.backgroundTertiary
                    : `linear-gradient(135deg, ${theme.colors.success} 0%, #059669 100%)`,
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: '600',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  transition: 'all 0.2s ease',
                  boxShadow: isSubmittingBid ? 'none' : `0 4px 12px ${theme.colors.success}40`,
                  opacity: isSubmittingBid ? 0.7 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.transform = 'translateY(-2px)')}
                onMouseLeave={(e) => (e.currentTarget.style.transform = 'translateY(0)')}
              >
                {isSubmittingBid ? (
                  <>
                    <Loader size={16} style={{ animation: 'spin 1s linear infinite' }} />
                    Submitting Bid...
                  </>
                ) : (
                  <>
                    <CheckCircle size={16} />
                    Submit Bid
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </PageContainer>
  )
}

export default CarrierLoadBoardPage

