import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTheme } from '../contexts/ThemeContext'
import PageContainer from '../components/PageContainer'
import Card from '../components/Card'
import { formatNumber, formatCurrency, formatCompactCurrency, formatPercentage } from '../utils/formatters';

import { 
  Truck, Package, MapPin, DollarSign, Clock, TrendingUp, 
  AlertCircle, CheckCircle, Filter, Search, Eye, 
  Calendar, Navigation, Zap, Star, Loader, Send, X, Building
} from 'lucide-react'

// Load Board Listing Interface - Shows limited info for security
interface LoadBoardListing {
  id: string // Auto-generated by system
  contractDate: string // When customer posted load
  customer: string // Customer name
  commodity: string // Material type
  equipment: string // Equipment needed
  
  // Pickup Info (CITY ONLY - security feature)
  pickupCity: string // Only city shown on board
  pickupState: string
  pickupDate: string // Separate date field
  pickupETA: string // Separate time window
  
  // Delivery Info (CITY ONLY - security feature)  
  deliveryCity: string // Only city shown on board
  deliveryState: string
  deliveryDate: string // Separate date field
  deliveryETA: string // Separate time window
  
  // Financial
  rateMode: 'PER_TON' | 'PER_LOAD' | 'PER_MILE' | 'PER_YARD'
  rate: number // Numeric rate
  units: number // Tonnage, loads, etc.
  estimatedRevenue: number
  
  // Logistics
  mileage: number // Distance
  
  // Additional
  requirements: string[]
  priority: 'high' | 'medium' | 'low'
  quickPayEligible: boolean
  
  // Full details (hidden until bid accepted)
  fullPickupAddress?: string
  fullDeliveryAddress?: string
  pickupContact?: { name: string; phone: string }
  deliveryContact?: { name: string; phone: string }
}

const CarrierLoadBoardPage = () => {
  const navigate = useNavigate()
  const { theme } = useTheme()
  
  const [loads, setLoads] = useState<LoadBoardListing[]>([])
  const [loading, setLoading] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterEquipment, setFilterEquipment] = useState('all')
  const [filterPriority, setFilterPriority] = useState('all')
  const [selectedLoad, setSelectedLoad] = useState<LoadBoardListing | null>(null)
  const [showBidModal, setShowBidModal] = useState(false)
  const [bidAmount, setBidAmount] = useState('')
  const [bidNotes, setBidNotes] = useState('')
  const [isSubmittingBid, setIsSubmittingBid] = useState(false)

  // Mock data - matches your workflow spec
  const mockLoads: LoadBoardListing[] = [
    {
      id: 'LT-2025-0001',
      contractDate: '2025-10-09',
      customer: 'ABC Construction',
      commodity: 'Crushed Limestone',
      equipment: 'End Dump',
      pickupCity: 'Austin',
      pickupState: 'TX',
      pickupDate: '2025-10-15',
      pickupETA: '8:00 AM - 10:00 AM',
      deliveryCity: 'San Antonio',
      deliveryState: 'TX',
      deliveryDate: '2025-10-15',
      deliveryETA: '2:00 PM - 4:00 PM',
      rateMode: 'PER_TON',
      rate: 75,
      units: 18.5,
      estimatedRevenue: 1387.50,
      mileage: 80,
      requirements: ['Scale Ticket Required', 'DOT Compliant'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '1234 Quarry Rd, Austin, TX 78701',
      fullDeliveryAddress: '5678 Construction Site, San Antonio, TX 78205',
      pickupContact: { name: 'Tom Martinez', phone: '(512) 555-0123' },
      deliveryContact: { name: 'John Foreman', phone: '(210) 555-0456' }
    },
    {
      id: 'LT-2025-0002',
      contractDate: '2025-10-09',
      customer: 'Downtown Builders',
      commodity: 'Concrete Mix (3000 PSI)',
      equipment: 'Mixer',
      pickupCity: 'Round Rock',
      pickupState: 'TX',
      pickupDate: '2025-10-16',
      pickupETA: '6:00 AM - 8:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-16',
      deliveryETA: '10:00 AM - 12:00 PM',
      rateMode: 'PER_YARD',
      rate: 180,
      units: 8,
      estimatedRevenue: 1440,
      mileage: 22,
      requirements: ['Time Sensitive (90min limit)', 'Pour scheduled'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '789 Plant Rd, Round Rock, TX 78664',
      fullDeliveryAddress: '321 Downtown Site, Austin, TX 78701',
      pickupContact: { name: 'Plant Manager', phone: '(512) 555-0789' },
      deliveryContact: { name: 'Site Foreman', phone: '(512) 555-0321' }
    },
    {
      id: 'LT-2025-0003',
      contractDate: '2025-10-08',
      customer: 'Highway Construction LLC',
      commodity: 'Gravel Base',
      equipment: 'End Dump',
      pickupCity: 'Georgetown',
      pickupState: 'TX',
      pickupDate: '2025-10-14',
      pickupETA: '7:00 AM - 9:00 AM',
      deliveryCity: 'Pflugerville',
      deliveryState: 'TX',
      deliveryDate: '2025-10-14',
      deliveryETA: '11:00 AM - 1:00 PM',
      rateMode: 'PER_TON',
      rate: 52,
      units: 25,
      estimatedRevenue: 1300,
      mileage: 18,
      requirements: ['Scale Ticket Required'],
      priority: 'medium',
      quickPayEligible: false,
      fullPickupAddress: '456 Gravel Pit Rd, Georgetown, TX 78626',
      fullDeliveryAddress: '789 Highway 130, Pflugerville, TX 78660',
      pickupContact: { name: 'Pit Supervisor', phone: '(512) 555-0456' },
      deliveryContact: { name: 'Highway Crew Lead', phone: '(512) 555-0789' }
    },
    {
      id: 'LT-2025-0004',
      contractDate: '2025-10-09',
      customer: 'Metro Development Corp',
      commodity: 'Ready-Mix Concrete (4000 PSI)',
      equipment: 'Mixer',
      pickupCity: 'Austin',
      pickupState: 'TX',
      pickupDate: '2025-10-17',
      pickupETA: '5:00 AM - 7:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-17',
      deliveryETA: '8:00 AM - 10:00 AM',
      rateMode: 'PER_YARD',
      rate: 195,
      units: 12,
      estimatedRevenue: 2340,
      mileage: 8,
      requirements: ['Time Sensitive (90min limit)', 'Early Morning Pour'],
      priority: 'high',
      quickPayEligible: true,
      fullPickupAddress: '123 Concrete Plant, Austin, TX 78704',
      fullDeliveryAddress: '456 Metro Tower Site, Austin, TX 78701',
      pickupContact: { name: 'Batch Plant Operator', phone: '(512) 555-0111' },
      deliveryContact: { name: 'Pour Coordinator', phone: '(512) 555-0222' }
    },
    {
      id: 'LT-2025-0005',
      contractDate: '2025-10-07',
      customer: 'Riverside Contractors',
      commodity: 'Sand',
      equipment: 'End Dump',
      pickupCity: 'Bastrop',
      pickupState: 'TX',
      pickupDate: '2025-10-12',
      pickupETA: '9:00 AM - 11:00 AM',
      deliveryCity: 'Austin',
      deliveryState: 'TX',
      deliveryDate: '2025-10-12',
      deliveryETA: '1:00 PM - 3:00 PM',
      rateMode: 'PER_TON',
      rate: 38,
      units: 22,
      estimatedRevenue: 836,
      mileage: 32,
      requirements: ['Scale Ticket Required', 'Tarp Required'],
      priority: 'low',
      quickPayEligible: false,
      fullPickupAddress: '999 Sand Pit Ln, Bastrop, TX 78602',
      fullDeliveryAddress: '555 Riverside Project, Austin, TX 78702',
      pickupContact: { name: 'Pit Manager', phone: '(512) 555-0999' },
      deliveryContact: { name: 'Project Manager', phone: '(512) 555-0555' }
    }
  ]

  React.useEffect(() => {
    // Load data
    setLoads(mockLoads)
  }, [])

  const handleSubmitBid = async () => {
    if (!selectedLoad) return
    
    setIsSubmittingBid(true)
    
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      console.log('Bid submitted:', {
        loadId: selectedLoad.id,
        bidAmount: bidAmount || 'Posted Rate',
        notes: bidNotes
      })
      
      alert(
        `✅ BID SUBMITTED SUCCESSFULLY!\n\n` +
        `Load: ${selectedLoad.id}\n` +
        `Customer: ${selectedLoad.customer}\n` +
        `Your Bid: $${bidAmount || selectedLoad.estimatedRevenue}\n\n` +
        `Customer will review your bid.\n` +
        `You'll be notified when accepted.\n\n` +
        `Next Steps:\n` +
        `1. Customer accepts bid\n` +
        `2. Rate Confirmation automatically generated & sent\n` +
        `3. You sign as dispatch/owner (30 min deadline)\n` +
        `4. Driver has 30 MINUTES to accept via SMS\n` +
        `5. Load moves to "My Loads" with full details\n\n` +
        `📄 Rate Con will be sent to both you and your driver automatically!`
      )
      
      setShowBidModal(false)
      setSelectedLoad(null)
      setBidAmount('')
      setBidNotes('')
    } catch (error) {
      console.error('Error submitting bid:', error)
      alert('❌ Error submitting bid. Please try again.')
    } finally {
      setIsSubmittingBid(false)
    }
  }

  const filteredLoads = mockLoads.filter(load => {
    const matchesSearch = searchTerm === '' || 
      load.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      load.commodity.toLowerCase().includes(searchTerm.toLowerCase()) ||
      load.customer.toLowerCase().includes(searchTerm.toLowerCase()) ||
      load.pickupCity.toLowerCase().includes(searchTerm.toLowerCase()) ||
      load.deliveryCity.toLowerCase().includes(searchTerm.toLowerCase())
    
    const matchesEquipment = filterEquipment === 'all' || load.equipment === filterEquipment
    const matchesPriority = filterPriority === 'all' || load.priority === filterPriority
    
    return matchesSearch && matchesEquipment && matchesPriority
  })

  const stats = {
    total: mockLoads.length,
    available: mockLoads.length,
    totalRevenue: mockLoads.reduce((sum, l) => sum + l.estimatedRevenue, 0),
    quickPayEligible: mockLoads.filter(l => l.quickPayEligible).length,
    highPriority: mockLoads.filter(l => l.priority === 'high').length
  }

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return theme.colors.error
      case 'medium': return theme.colors.warning
      case 'low': return theme.colors.info
      default: return theme.colors.textSecondary
    }
  }

  const getRateModeDisplay = (mode: string) => {
    return mode.replace('PER_', '/').toLowerCase()
  }

  return (
    <PageContainer title="Load Board" subtitle="Available loads from customers - Submit bids to win freight">
      {/* Stats Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px', marginBottom: '24px' }}>
        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: `${theme.colors.primary}20`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Package size={28} color={theme.colors.primary} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>AVAILABLE LOADS</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.total}</p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: `${theme.colors.success}20`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <DollarSign size={28} color={theme.colors.success} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>TOTAL REVENUE</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>${(stats.totalRevenue / 1000).toFixed(1)}k</p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: `${theme.colors.warning}20`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Zap size={28} color={theme.colors.warning} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>QUICKPAY</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.quickPayEligible}</p>
            </div>
          </div>
        </Card>

        <Card padding="24px">
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ width: '56px', height: '56px', borderRadius: '12px', backgroundColor: `${theme.colors.error}20`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Star size={28} color={theme.colors.error} />
            </div>
            <div style={{ flex: 1 }}>
              <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>HOT LOADS</p>
              <p style={{ fontSize: '36px', fontWeight: '700', color: theme.colors.textPrimary, margin: 0 }}>{stats.highPriority}</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Search and Filters */}
      <Card padding="20px" style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
          <div style={{ flex: '1 1 300px', position: 'relative' }}>
            <Search size={18} color={theme.colors.textSecondary} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              type="text"
              placeholder="Search by load ID, commodity, customer, or city..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{
                width: '100%',
                padding: '12px 12px 12px 42px',
                background: theme.colors.background,
                border: `1px solid ${theme.colors.border}`,
                borderRadius: '8px',
                color: theme.colors.textPrimary,
                fontSize: '14px',
                outline: 'none',
                transition: 'all 0.2s ease'
              }}
              onFocus={(e) => {
                e.target.style.borderColor = theme.colors.primary
                e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
              }}
              onBlur={(e) => {
                e.target.style.borderColor = theme.colors.border
                e.target.style.boxShadow = 'none'
              }}
            />
          </div>

          <select
            value={filterEquipment}
            onChange={(e) => setFilterEquipment(e.target.value)}
            style={{
              padding: '12px 16px',
              background: theme.colors.backgroundCard,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: '8px',
              color: theme.colors.textPrimary,
              fontSize: '14px',
              cursor: 'pointer',
              outline: 'none',
              minWidth: '180px',
              transition: 'all 0.2s ease'
            }}
            onFocus={(e) => {
              e.target.style.borderColor = theme.colors.primary
              e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
            }}
            onBlur={(e) => {
              e.target.style.borderColor = theme.colors.border
              e.target.style.boxShadow = 'none'
            }}
          >
            <option value="all" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>All Equipment</option>
            <option value="End Dump" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>End Dump</option>
            <option value="Mixer" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Mixer</option>
            <option value="Flatbed" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Flatbed</option>
            <option value="Lowboy" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Lowboy</option>
          </select>

          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            style={{
              padding: '12px 16px',
              background: theme.colors.backgroundCard,
              border: `1px solid ${theme.colors.border}`,
              borderRadius: '8px',
              color: theme.colors.textPrimary,
              fontSize: '14px',
              cursor: 'pointer',
              outline: 'none',
              minWidth: '180px',
              transition: 'all 0.2s ease'
            }}
            onFocus={(e) => {
              e.target.style.borderColor = theme.colors.primary
              e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
            }}
            onBlur={(e) => {
              e.target.style.borderColor = theme.colors.border
              e.target.style.boxShadow = 'none'
            }}
          >
            <option value="all" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>All Priority</option>
            <option value="high" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>High Priority</option>
            <option value="medium" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Medium Priority</option>
            <option value="low" style={{ background: theme.colors.backgroundCard, color: theme.colors.textPrimary }}>Low Priority</option>
          </select>
        </div>
      </Card>

      {/* Loads List */}
      <Card padding="20px">
        <h3 style={{ fontSize: '18px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 20px 0' }}>
          Available Loads ({filteredLoads.length})
        </h3>

        {filteredLoads.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px 20px' }}>
            <Package size={48} color={theme.colors.textSecondary} style={{ opacity: 0.5 }} />
            <p style={{ marginTop: '16px', color: theme.colors.textSecondary }}>No loads found matching your filters</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {filteredLoads.map((load) => (
              <div
                key={load.id}
                style={{
                  background: theme.colors.backgroundCard,
                  borderRadius: '12px',
                  padding: '24px',
                  border: `2px solid ${load.priority === 'high' ? theme.colors.error : theme.colors.border}`,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.12)'
                  e.currentTarget.style.transform = 'translateY(-2px)'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.boxShadow = 'none'
                  e.currentTarget.style.transform = 'translateY(0)'
                }}
              >
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px', flexWrap: 'wrap' }}>
                      <span style={{ fontSize: '20px', fontWeight: '700', color: theme.colors.textPrimary }}>
                        {load.id}
                      </span>
                      {load.priority === 'high' && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.error}20`,
                          color: theme.colors.error,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          textTransform: 'uppercase',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Star size={12} />
                          HOT LOAD
                        </span>
                      )}
                      {load.quickPayEligible && (
                        <span style={{
                          padding: '4px 12px',
                          background: `${theme.colors.warning}20`,
                          color: theme.colors.warning,
                          borderRadius: '6px',
                          fontSize: '12px',
                          fontWeight: '600',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}>
                          <Zap size={12} />
                          QuickPay
                        </span>
                      )}
                    </div>
                    <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: '0 0 4px 0' }}>
                      <Building size={14} style={{ display: 'inline', marginRight: '6px' }} />
                      {load.customer} • Posted {load.contractDate}
                    </p>
                    <p style={{ fontSize: '16px', fontWeight: '600', color: theme.colors.textPrimary, margin: 0 }}>
                      {load.commodity} • {load.units} {load.rateMode.replace('PER_', '').toLowerCase()}{load.units > 1 ? 's' : ''}
                    </p>
                  </div>

                  <div style={{ textAlign: 'right' }}>
                    <p style={{ fontSize: '28px', fontWeight: '700', color: theme.colors.success, margin: '0 0 4px 0' }}>
                      ${formatNumber(load.estimatedRevenue)}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: 0 }}>
                      ${load.rate}{getRateModeDisplay(load.rateMode)}
                    </p>
                  </div>
                </div>

                {/* Route Info - CITY ONLY (Security Feature) */}
                <div style={{ 
                  display: 'grid', 
                  gridTemplateColumns: '1fr auto 1fr', 
                  gap: '16px', 
                  alignItems: 'center',
                  padding: '16px',
                  background: theme.colors.background,
                  borderRadius: '8px',
                  marginBottom: '16px'
                }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                      <MapPin size={16} color={theme.colors.success} />
                      <span style={{ fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, textTransform: 'uppercase' }}>
                        Pickup
                      </span>
                    </div>
                    <p style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                      {load.pickupCity}, {load.pickupState}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: '0 0 2px 0' }}>
                      <Clock size={12} style={{ display: 'inline', marginRight: '4px' }} />
                      {load.pickupDate}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textTertiary, margin: 0 }}>
                      {load.pickupETA}
                    </p>
                    <p style={{ fontSize: '11px', color: theme.colors.textTertiary, margin: '4px 0 0 0', fontStyle: 'italic' }}>
                      * Full address in Rate Con
                    </p>
                  </div>

                  <div style={{ textAlign: 'center' }}>
                    <Navigation size={20} color={theme.colors.primary} />
                    <p style={{ fontSize: '14px', fontWeight: '600', color: theme.colors.textPrimary, margin: '4px 0 0 0' }}>
                      {load.mileage} mi
                    </p>
                  </div>

                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
                      <MapPin size={16} color={theme.colors.error} />
                      <span style={{ fontSize: '12px', fontWeight: '600', color: theme.colors.textSecondary, textTransform: 'uppercase' }}>
                        Delivery
                      </span>
                    </div>
                    <p style={{ fontSize: '16px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                      {load.deliveryCity}, {load.deliveryState}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textSecondary, margin: '0 0 2px 0' }}>
                      <Clock size={12} style={{ display: 'inline', marginRight: '4px' }} />
                      {load.deliveryDate}
                    </p>
                    <p style={{ fontSize: '13px', color: theme.colors.textTertiary, margin: 0 }}>
                      {load.deliveryETA}
                    </p>
                    <p style={{ fontSize: '11px', color: theme.colors.textTertiary, margin: '4px 0 0 0', fontStyle: 'italic' }}>
                      * Full address in Rate Con
                    </p>
                  </div>
                </div>

                {/* Equipment & Requirements */}
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap', marginBottom: '16px' }}>
                  <div style={{
                    padding: '6px 12px',
                    background: `${theme.colors.info}20`,
                    border: `1px solid ${theme.colors.info}`,
                    borderRadius: '6px',
                    fontSize: '13px',
                    fontWeight: '600',
                    color: theme.colors.info,
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px'
                  }}>
                    <Truck size={14} />
                    {load.equipment}
                  </div>

                  {load.requirements.map((req, idx) => (
                    <span
                      key={idx}
                      style={{
                        padding: '6px 12px',
                        background: `${theme.colors.warning}15`,
                        border: `1px solid ${theme.colors.warning}30`,
                        color: theme.colors.textSecondary,
                        borderRadius: '6px',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <AlertCircle size={12} />
                      {req}
                    </span>
                  ))}
                </div>

                {/* Action Button */}
                <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                  <button
                    onClick={() => {
                      setSelectedLoad(load)
                      setShowBidModal(true)
                    }}
                    style={{
                      padding: '12px 24px',
                      background: `linear-gradient(135deg, ${theme.colors.primary} 0%, #b91c1c 100%)`,
                      color: 'white',
                      border: 'none',
                      borderRadius: '8px',
                      fontSize: '14px',
                      fontWeight: '600',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '8px',
                      transition: 'all 0.2s ease',
                      boxShadow: `0 4px 12px ${theme.colors.primary}40`
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.transform = 'translateY(-2px)'
                      e.currentTarget.style.boxShadow = `0 6px 16px ${theme.colors.primary}60`
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.transform = 'translateY(0)'
                      e.currentTarget.style.boxShadow = `0 4px 12px ${theme.colors.primary}40`
                    }}
                  >
                    <Send size={16} />
                    Submit Bid
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Bid Submission Modal */}
      {showBidModal && selectedLoad && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'rgba(0, 0, 0, 0.75)',
            backdropFilter: 'blur(4px)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '20px'
          }}
          onClick={() => !isSubmittingBid && setShowBidModal(false)}
        >
          <div
            onClick={(e) => e.stopPropagation()}
            style={{
              background: theme.colors.backgroundCard,
              borderRadius: '16px',
              maxWidth: '700px',
              width: '100%',
              maxHeight: '90vh',
              overflow: 'auto',
              boxShadow: '0 24px 48px rgba(0, 0, 0, 0.3)'
            }}
          >
            {/* Modal Header */}
            <div style={{ padding: '24px', borderBottom: `1px solid ${theme.colors.border}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div>
                <h2 style={{ fontSize: '22px', fontWeight: '700', color: theme.colors.textPrimary, margin: '0 0 4px 0' }}>
                  Submit Bid
                </h2>
                <p style={{ fontSize: '14px', color: theme.colors.textSecondary, margin: 0 }}>
                  {selectedLoad.id} - {selectedLoad.commodity}
                </p>
              </div>
              <button
                onClick={() => !isSubmittingBid && setShowBidModal(false)}
                disabled={isSubmittingBid}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  padding: '8px',
                  borderRadius: '6px',
                  transition: 'all 0.2s ease',
                  opacity: isSubmittingBid ? 0.5 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.background = theme.colors.backgroundCardHover)}
                onMouseLeave={(e) => (e.currentTarget.style.background = 'none')}
              >
                <X size={24} color={theme.colors.textSecondary} />
              </button>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px' }}>
              {/* Load Summary */}
              <div style={{ padding: '16px', background: theme.colors.background, borderRadius: '12px', marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '12px' }}>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>CUSTOMER</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.customer}</p>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>POSTED</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.contractDate}</p>
                  </div>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>ROUTE</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0 }}>
                      {selectedLoad.pickupCity} → {selectedLoad.deliveryCity} ({selectedLoad.mileage} mi)
                    </p>
                  </div>
                  <div>
                    <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: '0 0 4px 0', fontWeight: '600' }}>EQUIPMENT</p>
                    <p style={{ fontSize: '14px', color: theme.colors.textPrimary, margin: 0, fontWeight: '600' }}>{selectedLoad.equipment}</p>
                  </div>
                </div>
              </div>

              {/* Security Notice */}
              <div style={{
                padding: '12px 16px',
                background: `${theme.colors.warning}10`,
                border: `1px solid ${theme.colors.warning}30`,
                borderRadius: '8px',
                marginBottom: '24px',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '12px'
              }}>
                <AlertCircle size={18} color={theme.colors.warning} style={{ flexShrink: 0, marginTop: '2px' }} />
                <div>
                  <p style={{ fontSize: '13px', fontWeight: '600', color: theme.colors.warning, margin: '0 0 4px 0' }}>
                    Address Privacy Notice
                  </p>
                  <p style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: 0, lineHeight: 1.5 }}>
                    Full pickup & delivery addresses, along with contact information, will be revealed in the Rate Confirmation after your bid is accepted by the customer.
                  </p>
                </div>
              </div>

              {/* Bid Amount */}
              <div style={{ marginBottom: '20px' }}>
                <label style={{
                  fontSize: '14px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  display: 'block',
                  marginBottom: '8px'
                }}>
                  Your Bid Amount (Optional)
                </label>
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: theme.colors.textSecondary, fontSize: '14px', fontWeight: '600' }}>$</span>
                  <input
                    type="number"
                    value={bidAmount}
                    onChange={(e) => setBidAmount(e.target.value)}
                    placeholder={selectedLoad.estimatedRevenue.toString()}
                    disabled={isSubmittingBid}
                    style={{
                      width: '100%',
                      padding: '12px 12px 12px 28px',
                      background: theme.colors.background,
                      border: `1px solid ${theme.colors.border}`,
                      borderRadius: '8px',
                      color: theme.colors.textPrimary,
                      fontSize: '16px',
                      fontWeight: '600',
                      outline: 'none',
                      transition: 'all 0.2s ease'
                    }}
                    onFocus={(e) => {
                      e.target.style.borderColor = theme.colors.primary
                      e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                    }}
                    onBlur={(e) => {
                      e.target.style.borderColor = theme.colors.border
                      e.target.style.boxShadow = 'none'
                    }}
                  />
                </div>
                <p style={{ fontSize: '12px', color: theme.colors.textTertiary, margin: '6px 0 0 0' }}>
                  Tip: Leave blank to bid at posted rate (${formatNumber(selectedLoad.estimatedRevenue)})
                </p>
              </div>

              {/* Bid Notes */}
              <div style={{ marginBottom: '24px' }}>
                <label style={{
                  fontSize: '14px',
                  fontWeight: '600',
                  color: theme.colors.textPrimary,
                  display: 'block',
                  marginBottom: '8px'
                }}>
                  Notes to Customer (Optional)
                </label>
                <textarea
                  value={bidNotes}
                  onChange={(e) => setBidNotes(e.target.value)}
                  placeholder="Add any questions, special capabilities, or notes for the customer..."
                  disabled={isSubmittingBid}
                  rows={4}
                  style={{
                    width: '100%',
                    padding: '12px',
                    background: theme.colors.background,
                    border: `1px solid ${theme.colors.border}`,
                    borderRadius: '8px',
                    color: theme.colors.textPrimary,
                    fontSize: '14px',
                    outline: 'none',
                    resize: 'vertical',
                    fontFamily: 'inherit',
                    transition: 'all 0.2s ease'
                  }}
                  onFocus={(e) => {
                    e.target.style.borderColor = theme.colors.primary
                    e.target.style.boxShadow = `0 0 0 3px ${theme.colors.primary}20`
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = theme.colors.border
                    e.target.style.boxShadow = 'none'
                  }}
                />
              </div>

              {/* Workflow Info */}
              <div style={{
                padding: '16px',
                background: `${theme.colors.info}10`,
                border: `1px solid ${theme.colors.info}30`,
                borderRadius: '8px',
                marginBottom: '24px'
              }}>
                <p style={{ fontSize: '13px', fontWeight: '600', color: theme.colors.info, margin: '0 0 8px 0' }}>
                  Next Steps After Bid Submission:
                </p>
                <ol style={{ fontSize: '12px', color: theme.colors.textSecondary, margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  <li>Customer reviews your bid</li>
                  <li>If accepted, Rate Confirmation is generated</li>
                  <li>You (dispatch/owner) sign Rate Confirmation</li>
                  <li>Driver receives SMS and has <strong style={{ color: theme.colors.error }}>30 MINUTES</strong> to accept</li>
                  <li>If accepted, load moves to "My Loads" with full details</li>
                  <li>If not accepted in 30 min, load returns to Load Board</li>
                </ol>
              </div>
            </div>

            {/* Modal Footer */}
            <div style={{ padding: '20px 24px', borderTop: `1px solid ${theme.colors.border}`, display: 'flex', gap: '12px', justifyContent: 'flex-end' }}>
              <button
                onClick={() => {
                  setShowBidModal(false)
                  setSelectedLoad(null)
                  setBidAmount('')
                  setBidNotes('')
                }}
                disabled={isSubmittingBid}
                style={{
                  padding: '12px 24px',
                  background: theme.colors.backgroundTertiary,
                  color: theme.colors.textPrimary,
                  border: `1px solid ${theme.colors.border}`,
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: '600',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s ease',
                  opacity: isSubmittingBid ? 0.5 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.background = theme.colors.backgroundCardHover)}
                onMouseLeave={(e) => (e.currentTarget.style.background = theme.colors.backgroundTertiary)}
              >
                Cancel
              </button>
              <button
                onClick={handleSubmitBid}
                disabled={isSubmittingBid}
                style={{
                  padding: '12px 28px',
                  background: isSubmittingBid
                    ? theme.colors.backgroundTertiary
                    : `linear-gradient(135deg, ${theme.colors.success} 0%, #059669 100%)`,
                  color: 'white',
                  border: 'none',
                  borderRadius: '8px',
                  fontSize: '14px',
                  fontWeight: '600',
                  cursor: isSubmittingBid ? 'not-allowed' : 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  transition: 'all 0.2s ease',
                  boxShadow: isSubmittingBid ? 'none' : `0 4px 12px ${theme.colors.success}40`,
                  opacity: isSubmittingBid ? 0.7 : 1
                }}
                onMouseEnter={(e) => !isSubmittingBid && (e.currentTarget.style.transform = 'translateY(-2px)')}
                onMouseLeave={(e) => (e.currentTarget.style.transform = 'translateY(0)')}
              >
                {isSubmittingBid ? (
                  <>
                    <Loader size={16} style={{ animation: 'spin 1s linear infinite' }} />
                    Submitting Bid...
                  </>
                ) : (
                  <>
                    <CheckCircle size={16} />
                    Submit Bid
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </PageContainer>
  )
}

export default CarrierLoadBoardPage

